### ISSUE TITLE
Rust slice

### ISSUE THREAD

**Issue by programmerjake** [dtolnay/cxx#10]
Maybe [`std::span`](https://en.cppreference.com/w/cpp/container/span) could be used as the translation of a Rust slice

**Comment by programmerjake** [comment]
You could use `&[T]` -> `std::span<const T>` and `&mut [T]` -> `std::span<T>`.

**Comment by bitwalker** [comment]
Yeah this is the main thing holding me back at the moment myself, I have code I'd like to port to use `cxx`, but it involves passing around slices/vectors frequently.

I started looking into what an implementation would take, and I don't _think_ it would be too difficult to get something working, but unfortunately I can't spare the time at the moment, so I'll have to revisit in a few weeks and see if things are still in limbo.

RE: `std::span` - it is only in C++20, so I don't think it's the best option in the near term (though it could be conditionally enabled if available). I'd think something akin to the way `&str` is handled would apply here. As long as the C++ implementation provides the iterator traits, it wouldn't make much of a difference in ergonomics.

**Comment by adetaylor** [comment]
I made an attempt at some progress here: https://github.com/dtolnay/cxx/pull/117

**Comment by dtolnay** [comment]
`&[u8]` support was released in cxx 0.2.9, `&mut [u8]` in 1.0.3, and `&[T]` / `&mut [T]` for T!=u8 in 1.0.5, so we should be all done here!
