### ISSUE TITLE
How to get UniquePtr<EnumMember> on the Rust side? 

### ISSUE THREAD

**Issue by lucas-zee** [dtolnay/cxx#1007]
I have the following struct on Rust:

```

#[cxx::bridge]
pub(crate) mod ffi {
    enum SizeType {
        BYTE,
        WORD,
        DWORD,
        QWORD,
    }
     unsafe extern "C++" {
         //...
     }
}
```

which is also mapped on C++. How do I get `UniquePtr<SizeType>` on Rust? Do I have to write a C++ function to get it? If I do, there's no point in having the struct on the Rust side. 

I tried

`let byte_ptr = UniquePtr::new(SizeType::BYTE);`

but it does not work:

the trait bound bridge::ffi::SizeType: cxx::memory::UniquePtrTarget is not satisfied
the trait cxx::memory::UniquePtrTarget is not implemented for bridge::ffi::SizeType

**Comment by dtolnay** [comment]
Closing in favor of https://users.rust-lang.org/t/how-to-get-uniqueptr-enummember-on-the-rust-side/70954?u=dtolnay.
