### ISSUE TITLE
Unsupported raw pointer in namespaces

### ISSUE THREAD

**Issue by lerouxrgd** [dtolnay/cxx#1008]
Similarly to #796 I have the following situation:

```rs
#[cxx::bridge(namespace = foo)]
pub mod ffi {
    unsafe extern "C++" {
        include!("some/header.h"); // defines foo::processOneFrame(const void *p);

        type c_void;

        unsafe fn processOneFrame(p: *const c_void);
}
```

Where the generated type is `::foo::c_void` instead of `::c_void` because of the `foo` namespace in the bridge.

Is there a workaround for this, or is it impossible to use `c_void` in a namespaced function/method ?

**Comment by dtolnay** [comment]
It'll work exactly the same as in that link. Though you need to be mindful that the typedef on the C++ side is in the namespace that the `extern "C++"` block on the Rust side says it's in. So you could either have `using c_void = void` inside namespace foo in C++ and the extern block as above, or you can have `using c_void = void` in the root namespace in C++ and an extern block that also refers to the root namespace:

```rust
#[cxx::bridge]
mod ffi {
    extern "C++" {
        type c_void;
    }

    #[namespace = "foo"]
    unsafe extern "C++" {
        // other stuff
    }
}
```

**Comment by lerouxrgd** [comment]
The latter worked perfectly, thank you !
