### ISSUE TITLE
Using `ExternType` for a type alias in an FFI generated by an external crate

### ISSUE THREAD

**Issue by 2pt0** [dtolnay/cxx#1017]
I hope this isn't a duplicate issue. I have read the documentation and I'm still a bit confused.

I am trying to call a C++ function which requires a Message Passing Interface (MPI) communicator from Rust. To this end, I am wanting to use the [`rsmpi`](https://github.com/rsmpi/rsmpi) crate to retrieve the FFI `MPI_Comm` `rsmpi` generates using bindgen. It seems that I still need to implement the `ExternType` for `MPI_Comm`. However, I am facing a few problems:

1. I am unable to implement a trait for a type not defined in my local crate. Would it be possible to wrap the `MPI_Comm` in a new struct to somehow pass the `MPI_Comm` to a C++ function? Could I use the FFI `MPI_Comm` defined by `rsmpi` somehow?
2. MPi is really just a specification and different vendors implement the specification in different ways. For example, MPICH simply represents a `MPI_Comm` using an `int` while OpenMPI uses a pointer to struct. Can `ExternType` be implemented for `MPI_Comm` in such a way that its underlying type implementation is unimportant?

This is the kind of interface I am trying to achieve (which of course doesn't compile):

```rust
// src/main.rs
use cxx::{type_id, ExternType};
use mpi::ffi::MPI_Comm;

unsafe impl ExternType for MPI_Comm {
    type Id = type_id!("MPI_Comm");
    type Kind = cxx::kind::Trivial;
}

#[cxx::bridge]
pub mod ffi {
    unsafe extern "C++" {
        include!("cxx-mpi-test/cxx/include/hello.hpp");

        fn hello(comm: MPI_Comm);
    }
}

fn main() {
    let universe = mpi::initialize().unwrap();
    let world = universe.world();

    ffi::hello(world.as_raw());
}
```

```cpp
// cxx/include/hello.hpp
#include <mpi.h>

void hello(MPI_Comm comm);
```

```cpp
// cxx/src/hello.cpp
#include <iostream>
#include "cxx-mpi-test/cxx/include/hello.hpp"

void hello(MPI_Comm comm) {
    int rank, size;
    MPI_Comm_rank(comm, &rank);
    MPI_Comm_size(comm, &size);
    std::cout << "Hello from " << rank << " of " << size << std::endl;
}
```

Am I missing something? Is there a better way to approach this problem? Thanks!

**Comment by 2pt0** [comment]
I have received the desired output by wrapping the `mpi::ffi::MPI_Comm` in the tuple struct `Comm`. I then implemented `ExternType` for `Comm` as though it were a `MPI_Comm`. This seems reasonable to me since I expect that `Comm` has the same size and alignment as `MPI_Comm`. Is this something I can rely on?

Still, I suspect there may be some unsoundness here since this feels a bit hacky. I've included my updated `main.rs`. The C++ code is unchanged.

```rust
// src/main.rs
use cxx::{type_id, ExternType};
use mpi::ffi::MPI_Comm;
use mpi::traits::*;

pub struct Comm(MPI_Comm);

unsafe impl ExternType for Comm {
    type Id = type_id!("MPI_Comm");
    type Kind = cxx::kind::Trivial;
}

#[cxx::bridge]
pub mod ffi {
    unsafe extern "C++" {
        include!("cxx-mpi-test/cxx/include/hello.hpp");

        type MPI_Comm = crate::Comm;

        fn hello(comm: MPI_Comm);
    }
}

fn main() {
    let universe = mpi::initialize().unwrap();
    let world = universe.world();

    let comm = Comm(world.as_raw());
    ffi::hello(comm);
}
```

**Comment by dtolnay** [comment]
You need a `#[repr(C)]` attribute on `Comm` or else the struct layout is not guaranteed to be the same as on the C++ side, but other than that the code in your last comment looks fine to me.

**Comment by 2pt0** [comment]
Thanks for the reply. I actually made that change this morning after reading more about type representations in Rust. Compile-time sanity tests pass too:

``` rust
use mpi::ffi::MPI_Comm;
use static_assertions::{assert_eq_align, assert_eq_size};

#[repr(C)]
pub struct Comm(MPI_Comm);

assert_eq_align!(Comm, MPI_Comm);
assert_eq_size!(Comm, MPI_Comm);
```
