### ISSUE TITLE
bazel: build fails if importing project's workspace sets default rust edition of "2021"

### ISSUE THREAD

**Issue by silas-enf** [dtolnay/cxx#1031]
With the following relevant bits in my project's workspace:
```bazel
##### TOOLCHAIN: RUST and dependencies
http_archive(
    name = "rules_rust",
    sha256 = "7453856d239a004c9e29cde2e45903a068446e4a69501ee7393faf08e1a30403",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_rust/releases/download/0.1.0/rules_rust-v0.1.0.tar.gz",
        "https://github.com/bazelbuild/rules_rust/releases/download/0.1.0/rules_rust-v0.1.0.tar.gz",
    ],
)

RUST_VERSION = "1.58.1"

load("@rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories(
    edition = "2021",
    version = RUST_VERSION,
)

##### cxx-rust-bridge dependencies
http_archive(
    name = "cxx.rs",
    sha256 = "4f27a01b3708f75d3f6f32b22cd9f407ebf1f419922e1b4aa1d78d320cd9844e",
    strip_prefix = "cxx-1.0.66",
    url = "https://github.com/dtolnay/cxx/archive/refs/tags/1.0.66.tar.gz",
)

load("@cxx.rs//tools/bazel:vendor.bzl", "vendor")

vendor(
    name = "third-party",
    cargo_version = RUST_VERSION,
    lockfile = "@cxx.rs//third-party:Cargo.lock",
)
```

I get the following compile error trying to build something depending on a cxx.rs rule:
```none
INFO: Found 1 target...
ERROR: /home/silas/.cache/bazel/_bazel_silas/256045c792efa47d51191a8cb06040d8/external/cxx.rs/third-party/BUILD:82:13: Compiling Rust rlib proc-macro2 (6 files) [for host] failed: (Exit 1): process_wrapper failed: error executing command bazel-out/host/bin/external/rules_rust/util/process_wrapper/process_wrapper --env-file bazel-out/host/bin/external/cxx.rs/third-party/proc-macro2@build.env --arg-file ... (remaining 32 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
error: `$pat:pat` is followed by `|`, which is not allowed for `pat` fragments
   --> external/cxx.rs/third-party/vendor/proc-macro2-1.0.36/src/parse.rs:536:32
    |
536 |     ($chars:ident @ $pat:pat $(| $rest:pat)*) => {
    |                                ^ not allowed after `pat` fragments
    |
    = note: allowed there are: `=>`, `,`, `=`, `if` or `in`

error: aborting due to previous error
```

This seems to be [an edition issue](https://doc.rust-lang.org/edition-guide/rust-2021/or-patterns-macro-rules.html) due to change of the meaning of that syntax for rust 2021.

I spoke with the rules_rust developers on the bazel slack and they confirmed that targets from other repositories inheriting the importing project's workspace's default edition is normal and expected, and (therefore) that targets which need a particular rust edition that may be pulled into other projects should explicitly set the edition even if it matches the default set by the workspace in that project.

Assuming this is preferable to "fixing" this in `proc-macro2` itself (which would require a substantial bump of MSRV to get the `pat_param` symbol), it seems the third-party/BUILD file should just be updated to explicitly force `proc-macro2` to `edition=2018` -- this at least has worked for me in my own testing. Making a PR for this now.

**Comment by dtolnay** [comment]
> I spoke with the rules_rust developers on the bazel slack and they confirmed that targets from other repositories inheriting the importing project's workspace's default edition is normal and expected

Could you clarify whether "normal and expected" means "desired behavior" or "undesirable behavior but unfixable"? It seems clearly undesirable to me. I think if it's not possible for a default edition to be set in a way that applies to all the places a workspace is imported into, perhaps `edition` should be changed to a required argument instead of allowing omitting it and guessing that another workspace's default will work.

**Comment by silas-enf** [comment]
Thanks for the quick response! I've been wondering the same thing. I will try to get some clarification on that.

**Comment by silas-enf** [comment]
So it does seem like this failure to set edition for the subtree seems like more an issue of how bazel works than how rules_rust works -- i.e. "undesirable but unfixable". It's not at all clear to me how one would fix the import case while retaining anything resembling the DRY/convenience that setting a default edition at the workspace level provides -- fwict you'd indeed need to make `edition` a required argument for every target as you suggest here.

I'll be opening up a ticket with rules_rust for further discussion (which I'll be sure to link here), but I suspect there's nothing better on their end than a docs fix (warning about the potential for issues like this), unless they're feeling really opinionated and want to remove `edition` from `rust_repositories` altogether.

**Comment by silas-enf** [comment]
Looks great; thanks for the fix!
