### ISSUE TITLE
Duplicate symbol when linking multiple staticlib

### ISSUE THREAD

**Issue by jason-yau** [dtolnay/cxx#1054]
When I use more than two rust static libraries built with cxx for my C++ project, it failed with following errors:
```bash
duplicate symbol '_cxxbridge1$rust_vec$f32$data' in:
    cxx/libbasic.a(cxx-6f92fa0cc8784bc2.cxx.25a7702b-cgu.5.rcgu.o)
    cxx/libsecond.a(cxx-50d76a46afddca83.cxx.7a1aee28-cgu.5.rcgu.o)
duplicate symbol '_cxxbridge1$slice$new' in:
    cxx/libbasic.a(cxx-6f92fa0cc8784bc2.cxx.25a7702b-cgu.8.rcgu.o)
    cxx/libsecond.a(cxx-50d76a46afddca83.cxx.7a1aee28-cgu.8.rcgu.o)
duplicate symbol '_cxxbridge1$slice$ptr' in:
    cxx/libbasic.a(cxx-6f92fa0cc8784bc2.cxx.25a7702b-cgu.8.rcgu.o)
    cxx/libsecond.a(cxx-50d76a46afddca83.cxx.7a1aee28-cgu.8.rcgu.o)
......
```
When I use just only one rust static library, It works. How do I solve this issue?

**Comment by dtolnay** [comment]
`staticlib` linking is discussed in https://cxx.rs/build/other.html#linking-the-c-and-rust-together.

**Comment by jason-yau** [comment]
> `staticlib` linking is discussed in https://cxx.rs/build/other.html#linking-the-c-and-rust-together.

I read. If I add only one rust static library to my c++ project, it works fine. But it fails with more than 2 rust static libraries. Because those libraries have same definitions. I think that those same definitions are generated by cxx.

**Comment by dtolnay** [comment]
I'll close because this is just how Rust staticlib linkage in general works, independent of cxx.

You can follow along https://github.com/rust-lang/rust/issues/73632 for other options.
