### ISSUE TITLE
Problem: using multiple cxx.rs libraries

### ISSUE THREAD

**Issue by leejw51crypto** [dtolnay/cxx#1056]
when i need to use multiple cxx.rs libraries,
it's dynamic library (dll) in windows.

i cannot link two cxx.rs libraries together for final binary  in visual studio 2022
```
ERROR: Unable to merge actions producing lib.rs.cc.o: prerequisites are different
ERROR: Unable to merge actions producing lib.rs.cc.o: command arguments are different
ERROR: Unable to merge actions producing lib.rs.cc.o: prerequisites are different
ERROR: Unable to merge actions producing lib.rs.cc.o: command arguments are different
ERROR: Action graph is invalid; unable to continue. See log for additional details
```
is there any workaround for this?

**Comment by dtolnay** [comment]
Sorry that no one was able to provide guidance here. I don't know anything about dll on Windows. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community.
