### ISSUE TITLE
Help with what to put in a main function for a cxx interface program

### ISSUE THREAD

**Issue by TennisBowling** [dtolnay/cxx#1070]
Hello, I'm currently making a program in rust that exposes a function to c++ using the cxx crate.
here is the program : https://gist.github.com/rust-play/0997aff926802eb98998273330d48a43
but I'm not sure what to put in the main function to make it callable from c++

**Comment by dtolnay** [comment]
From what you wrote in the Gist, I would expect the C++ main to look similar to this:

```cpp
#include "playground/playground.rs.h"

int main() {
  rust::Str token = "…";
  int64_t timestamp = …;
  rust::String jwt = rust_jwt::make_jwt(token, timestamp);
  (void)jwt;
}
```
