### ISSUE TITLE
Crate in Cargo registry fails tests

### ISSUE THREAD

**Issue by centromere** [dtolnay/cxx#1071]
The version of `cxx-test-suite` in the Cargo registry is over 2 years old.

![Screen Shot 2022-07-21 at 13 01 42](https://user-images.githubusercontent.com/543423/180272058-7640fe20-eb0d-4f79-93c0-d24e1aecd487.png)

<img width="944" alt="Screen Shot 2022-07-21 at 12 51 19" src="https://user-images.githubusercontent.com/543423/180272081-cf217f54-4126-4cc4-99e7-6448154bb79e.png">

**Comment by dtolnay** [comment]
I am not planning to regularly publish the test suite as a crates.io package.
