### ISSUE TITLE
Expose `cxxbridge-cmd` functionality programatically

### ISSUE THREAD

**Issue by conradoplg** [dtolnay/cxx#1080]
I have an unusual use case: I'm writing a Rust wrapper for C++ code that uses cxxbridge-cmd to generate bindings to Rust code (which is a dependency and not the exact thing I need to use).

The C++ code uses `cxxbridge-cmd` to generate the bindings, using `.h` extension for the headers.

Therefore the (outer) Rust wrapper needs to generate the same bindings. I'd like to use `cxx_build` programatically however the API is very high-level and won't allow me to use a `.h` extension (instead of `.rs.h`). This is required because the C++ code includes the binding header with e.g. `foo.h` and not `foo.rs.h`.

Thus I run `cxxbridge-cmd` manually, but that introduces an external dependency, which is annoying. If I could just to the same thing programatically using the crate, that would be much simpler.

Would you consider exposing the `cxxbridge-cmd` functionality in the `cxx_build` crate? Or is there any workaround for this issue?

Thanks!

**Comment by adetaylor** [comment]
Does https://docs.rs/cxx-gen/latest/cxx_gen/index.html help?

**Comment by dtolnay** [comment]
Trying to regenerate the same output that something in your dependency graph already generated is a red flag. You should directly include the one they generated instead.

https://cxx.rs/build/cargo.html#including-headers-from-dependencies talks about including headers from dependencies.

**Comment by conradoplg** [comment]
> Does https://docs.rs/cxx-gen/latest/cxx_gen/index.html help?

That solves it, not sure how I missed that, thanks a lot!

> Trying to regenerate the same output that something in your dependency graph already generated is a red flag. You should directly include the one they generated instead.
> 
> https://cxx.rs/build/cargo.html#including-headers-from-dependencies talks about including headers from dependencies.

I agree, but that applies to Rust dependencies, right? In my case it's a C++ dependency, so to make it generate the headers by itself I'd need to build it, which would require `make` etc. In any case I'm thinking about a better long-term solution, but this will do for now.
