### ISSUE TITLE
Binding to non-const method which returns const reference

### ISSUE THREAD

**Issue by bschwind** [dtolnay/cxx#1083]
Thank you for the library! ❤️

Apologies if this has been asked before, and maybe this is more of a C++ question than a CXX question.

I'm trying to write bindings to [OpenCascade](https://github.com/Open-Cascade-SAS/OCCT) (CAD kernel) and have run into a small issue I'm not sure how to resolve.

Here's a simplified version of the header file:

```c++
// BRepBuilderAPI_MakeEdge.hxx
class BRepBuilderAPI_MakeEdge  : public BRepBuilderAPI_MakeShape
{
public:
  Standard_EXPORT BRepBuilderAPI_MakeEdge();
  
  ...
  

  //! Returns the constructed edge.
  //! Exceptions StdFail_NotDone if the edge is not built.
  Standard_EXPORT const TopoDS_Edge& Edge();
  
  //! Returns the first vertex of the edge. May be Null.
  Standard_EXPORT const TopoDS_Vertex& Vertex1() const;
};
```

and the corresponding bridge code (ignoring the constructor)

```rust
// src/lib.rs
#[cxx::bridge]
pub mod ffi {
    unsafe extern "C++" {
        type BRepBuilderAPI_MakeEdge;
        type TopoDS_Vertex;
        type TopoDS_Edge;

        pub fn Edge(self: &BRepBuilderAPI_MakeEdge) -> &TopoDS_Edge;
        pub fn Vertex1(self: &BRepBuilderAPI_MakeEdge) -> &TopoDS_Vertex;
    }
}
```

I can bind to `Vertex1()` no problem, because the function is marked `const` (the trailing `const` defined in the header).

However I can't bind to `Edge()` because it's not marked as const. I get the following build output:

```
cargo:warning=/Users/brian/projects/opencascade/target/release/build/opencascade-sys-640032f072ecacd8/out/cxxbridge/sources/opencascade-sys/src/lib.rs.cc:121:53: error: cannot initialize a variable of type 'const ::TopoDS_Edge &(BRepBuilderAPI_MakeEdge::*)() const' with an rvalue of type 'const TopoDS_Edge &(BRepBuilderAPI_MakeEdge::*)()': different qualifiers ('const' vs unqualified)
  cargo:warning=  const ::TopoDS_Edge &(::BRepBuilderAPI_MakeEdge::*Edge$)() const = &::BRepBuilderAPI_MakeEdge::Edge;
  cargo:warning=                                                    ^                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1
```

The following code gets generated:

```c++
const ::TopoDS_Edge *cxxbridge1$BRepBuilderAPI_MakeEdge$Edge(const ::BRepBuilderAPI_MakeEdge &self) noexcept {
  const ::TopoDS_Edge &(::BRepBuilderAPI_MakeEdge::*Edge$)() const = &::BRepBuilderAPI_MakeEdge::Edge;
  return &(self.*Edge$)();
}
```

Now let's imagine I can modify the original source code. I simply add `const` at the end of the functions and all is well. Maybe I'll do that, but I'd like to avoid maintaining a fork.

Is there a way I can write a wrapper function such that this type check passes while still generating safe code? I tried that as well but got similar complaints about the wrapper function not being `const`, but it seems like I can't mark free-standing functions in C++ as `const`.

**Comment by dtolnay** [comment]
It sounds like you are asking how to write a non-const reference in a C++ signature? That is `&mut T` (for shared types) or `Pin<&mut T>` (for opaque C++ types).

```rust
        pub fn Edge(self: Pin<&mut BRepBuilderAPI_MakeEdge>) -> &TopoDS_Edge;
```

There shouldn't need to be any wrapper involved.

**Comment by bschwind** [comment]
> Pin<&mut T> (for opaque C++ types).

Ohhhhhhh, that's it! I'm really happy I opened this issue, I think I would have come up with something much more verbose.

Thanks for your help, and for CXX!

**Comment by mattiasunger** [comment]
I had the same issue which lead me here but if I replace I still can't make this work. I replaced
```rust
type Foo;
fn new_Foo() -> UniquePtr<Foo>;
fn Initialize(&self, path: &str) -> bool;
```
```cpp
class Foo
{
public:
	Foo();
    ~Foo();
    bool Initialize(rust::Str path) const;
};
```
with
```rust
type Foo;
fn new_Foo() -> UniquePtr<Foo>;
fn Initialize(self: Pin<&mut Foo>, path: &str) -> bool;
```
and removed the `const` from the cpp header and impl but that gave me.
```
no method named `Initialize` found for struct `UniquePtr<Foo>` in the current scope
```
If I used a pimpl pattern I can work around calling the const function but I think this would be a little cleaner (and less code).
Did something change since the last answer or have I missed something?

**Comment by bconn98** [comment]
I ran into the same issue. The solution is to save your pin as mutable, access the pin with `.as_mut().unwrap()`, and then you can operate on your object.

For example:
```rust
let mut foo = ffi::new_Foo();
foo.as_mut().unwrap().Initialize("my/path");
```
