### ISSUE TITLE
Specify/Add CXX include path

### ISSUE THREAD

**Issue by lennykovac** [dtolnay/cxx#1084]
Hello, is there a way to modify or add include paths for CXX. For now there are only two set. And with the [CFG.include_prefix](https://docs.rs/cxx-build/0.5.2/cxx_build/static.CFG.html#cfginclude_prefix) I wont be able to add new ones. 

CXX include path:

`
/home/kovac/rusty/target/debug/build/rusty-7bcd66ddb730b666/out/cxxbridge/include
`
`
/home/kovac/rusty/target/debug/build/rusty-7bcd66ddb730b666/out/cxxbridge/crate
`

**Comment by dtolnay** [comment]
This is explained in https://cxx.rs/build/cargo.html.
