### ISSUE TITLE
Issue cross compiling from mac to windows (mingw32)

### ISSUE THREAD

**Issue by SillyMoo** [dtolnay/cxx#1092]
If I cross compile to windows from my mac with:

`cd demo; cargo build -vvvv --target x86_64-pc-windows-gnu`

then when running up on windows I get the error "libstdc++-6.dll not found". I believe this is solvable by getting rustc to use `-static -static-libstdc++ -static-libgcc` but I can't see how that is possible.

Would be good to know if there is any solution for this that you are aware of, or if not any plans for the future that may resolve the issue.

**Comment by SillyMoo** [comment]
Worth noting, just tried this on linux too (again cross compiling to windows) same issue.

**Comment by dtolnay** [comment]
The `cc` crate passes CXXFLAGS through to the C++ compiler so you could try using `CXXFLAGS='-static -static-libstdc++ -static-libgcc' cargo build -vvvv --target x86_64-pc-windows-gnu`.

**Comment by SillyMoo** [comment]
Hi, sorry for the delay in responding. I tried this but it doesn't help. The problem is that this applies to the compilation phase but not to the linking phase. The linking is done through rustc (I'm using a cxx-build build script), and I can't find a way of forcing that to use static libstdc++.

**Comment by SillyMoo** [comment]
Ok, I've made progress. Added the following to my build.rs:

    let target: &str = &std::env::var("TARGET").unwrap();
    if target.ends_with("-pc-windows-gnu") {
        println!("cargo:rustc-link-lib=static:+whole-archive,+bundle=stdc++");
        println!("cargo:rustc-link-lib=static:+whole-archive,+bundle=pthread.dll");
    }
    
    This got a static link with stdc++, and also mean the only dll I had to copy across was libpthread.dll. Still can't get static compilation of libpthread working, but it feels that is more of a mingw issue than anything else.

**Comment by dtolnay** [comment]
If there's still guidance needed to get this working, please take this question to any of the resources shown in https://www.rust-lang.org/community.
