### ISSUE TITLE
[Windows] How to link bcrypt, userenv, etc?

### ISSUE THREAD

**Issue by casimcdaniels** [dtolnay/cxx#1097]
What is the proper way to link windows libraries (e.g. **bcrypt** or **userenv**) to the CXX output when compiling for Windows targets? I tried the following without success:

```rust
// build.rs

fn main () {
    cxx_build::bridge("src/lib.rs").compile("demo");

    println!("cargo:rustc-link-lib=userenv");
    println!("cargo:rustc-link-lib=bcrypt");
}
```

Using CMake to run cargo then link them with `target_link_libraries(demo bcrypt userenv ws2_32)` is an approach that works, but I was trying to avoid adding another build system into the mix and use only `cargo` if possible.

**Comment by dtolnay** [comment]
Sorry that no one was able to provide guidance here. I don't know anything about linkage on Windows. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community. I doubt there is anything about the link failure you saw that would be specific to `cxx`, as opposed to FFI in general, using `cc` and `bindgen` or anything else.
