### ISSUE TITLE
An example using structs from outside the "ffi" module

### ISSUE THREAD

**Issue by sayrer** [dtolnay/cxx#11]
I can't use this crate yet, because of its compiler requirements. But the examples left me wondering how to refer to structs that are not in the ffi module.

Is there a way to make a struct defined in another module, like this example:

```
pub struct NamedPoint {
  name: String,
  pub x: i32,
  pub y: i32,
}
```

visible to both languages, in the way that "SharedThing" is used in the example? Maybe a new annotation is needed for that?

**Comment by dtolnay** [comment]
I don't plan to support this. You need to either define the struct inside the ffi bridge to share its fields, or define it outside and treat it as an opaque Rust type with accessors for whichever fields the other language would require access to.

```rust
pub struct NamedPoint {
    name: String,
    x: i32,
    y: i32,
}

#[cxx::bridge]
mod ffi {
    extern "Rust" {
        type NamedPoint;
        fn named_point_x(pt: &NamedPoint) -> i32;
        fn named_point_y(pt: &NamedPoint) -> i32;
    }
}

fn named_point_x(pt: &NamedPoint) -> i32 { pt.x }
fn named_point_y(pt: &NamedPoint) -> i32 { pt.y }
```

**Comment by sayrer** [comment]
OK. I was only asking how to do it, not insisting on a solution. would your example work with 

```
fn named_point_name(pt: &NamedPoint) -> String;
```

that's the case I'm interested in.

**Comment by dtolnay** [comment]
Yes that would work exactly as you wrote it. I left it out because you left out `pub` on name at the top.

**Comment by sayrer** [comment]
My mistake, thanks. FWIW, an example showing this use case would be helpful, imho.
