### ISSUE TITLE
Add flags to build of cxx.o?

### ISSUE THREAD

**Issue by jthomas-dd** [dtolnay/cxx#1101]
I'm currently building a project using cxx with the wasm32-unknown-emscripten backend.

In order to enable threads, all linked .o files need to be compiled with '-pthread' which adds the '+.atomics' and '+.bulk-memory' options to the target-features section.

When using cxx.o, I can't seem to influence the flags provided to the compiler when building it, and end up getting the following error when linking:
`wasm-ld: error: --shared-memory is disallowed by cxx.o because it was not compiled with 'atomics' or 'bulk-memory' features.`

Is there any way for me to append to the build flags for cxx.o itself?

**Comment by dataO1** [comment]
I have the same problem, when trying to build a library that requires `-pthread` flag for the build. Did you find a solution yet? I've tried the cargo build script instructions, like `    println!("cargo:rustc-link-arg=-pthread");
` in the build.rs, but that did nothing.

**Comment by dtolnay** [comment]
The cc crate exposes CXXFLAGS for this purpose. See https://github.com/rust-lang/cc-rs/tree/1.0.73#external-configuration-via-environment-variables.

Could you try `CXXFLAGS=-pthread cargo build --target wasm32-unknown-emscripten`?
