### ISSUE TITLE
compile_commands.json generation?

### ISSUE THREAD

**Issue by GoldsteinE** [dtolnay/cxx#1118]
Hi! I was wondering if there any way to use `cxx` with `clangd`?

**Comment by dtolnay** [comment]
This would be a question for the cc crate. Cxx-build is ordinary and simple as far as use of the cc crate.

**Comment by HKalbasi** [comment]
For other people who come here by search, `bear -- cargo build` will generate the `compile_commands.json`, but you need something to trigger the build script of `cxx` (e.g. changing some cpp file, or using `cargo clean`) before it.

But it is still very manual. The cc related issue is https://github.com/rust-lang/cc-rs/issues/497
