### ISSUE TITLE
[Question] Cant this work with wasm?

### ISSUE THREAD

**Issue by trsh** [dtolnay/cxx#1121]
`wasm-pack build`

**Comment by dtolnay** [comment]
It does work with wasm (as long as you have a C++ standard library that supports wasm -- for example emscripten or wasi-sdk, although there are other ones that might also be viable).

For example I confirmed that https://github.com/dtolnay/cxx/tree/master/demo can be compiled to wasm32-unknown-emscripten and running the result produces the correct output on console.

**Comment by dtolnay** [comment]
![Screenshot from 2022-10-30 11-11-05](https://user-images.githubusercontent.com/1940490/198894395-58453681-7119-4b01-9142-a4a8b7db0ca3.png)

**Comment by trsh** [comment]
@dtolnay can you please share the workflow of how you compiled the demo to wasm32-unknown-emscripten ?

**Comment by dtolnay** [comment]
`cargo build --target wasm32-unknown-emscripten` in the demo directory. This produces demo.wasm, and a demo.js to load it, if you need that. For running in a browser here is a minimal HTML file:

```html
<!DOCTYPE html>
<script src="demo.js"></script>
<p>Open the console to see the output!</p>
```

**Comment by AlphaCodeZero** [comment]
@dtolnay I have a C++ project compiled to wasm by emscripten, is it possible to add some rust helper functions in that project with the help of cxx? Thanks in advance.

**Comment by dtolnay** [comment]
Yes that seems like a good fit for cxx because you are interested in calling Rust from C++, which is a thing that cxx is built for.

**Comment by DaveLomber** [comment]
@dtolnay 

I'm trying to compile the demo https://github.com/dtolnay/cxx/tree/master/demo for wasm under macOS

The command is the following:

```
cargo build --target=wasm32-wasi
```

But getting an error:

```
  cargo:warning=In file included from /Users/asd/workspace/cxx/src/cxx.cc:1:
  cargo:warning=/Users/asd/workspace/cxx/src/../include/cxx.h:2:10: fatal error: 'algorithm' file not found
  cargo:warning=    2 | #include <algorithm>
  cargo:warning=      |          ^~~~~~~~~~~
  cargo:warning=1 error generated.
```  
  
What could be wrong?
