### ISSUE TITLE
ManuallyDrop generate -Wshadow warnings

### ISSUE THREAD

**Issue by hfiguiere** [dtolnay/cxx#1124]
The generated code for `ManuallyDrop` is as follow:
```c++
template <typename T>
union ManuallyDrop {
  T value;
  ManuallyDrop(T &&value) : value(::std::move(value)) {}
  ~ManuallyDrop() {}
};
```

`value` is both a member and the argument name of the constructor triggering a warning with `-Wshadow`.

**Comment by hfiguiere** [comment]
cxx version 1.0.78

**Comment by dtolnay** [comment]
Closing along with https://github.com/dtolnay/cxx/pull/1125#pullrequestreview-1171713185.

Thanks anyway for the PR!
