### ISSUE TITLE
SharedPtr Copy trait

### ISSUE THREAD

**Issue by koliyo** [dtolnay/cxx#1127]
I am pretty new to rust and exploring the cxx bindings. First of all, thanks for this library, it seems very useful!

Question: Is there a reason that `cxx::SharedPtr` does not implement the `Copy` trait? I get this in my small test code when using the bindings:

```
    |       -- move occurs because `id` has type `SharedPtr<IdentifierTok>`, which does not implement the `Copy` trait
```

But copying a sharedptr should be a very common operation?

**Comment by dtolnay** [comment]
`Copy` means *"Types whose values can be duplicated simply by copying bits."* https://doc.rust-lang.org/std/marker/trait.Copy.html

Copying a shared_ptr is not a matter of copying the bits.
