### ISSUE TITLE
Add fields to CxxString, CxxVector, etc.

### ISSUE THREAD

**Issue by kytans** [dtolnay/cxx#1137]
Currently these structs are defined without fields, which makes it impossible to use them by value inside structs.

However, since the C++ code currently used to access them is fixed, fields must be in a specific layout anyway, so we could just as well specify fields in Rust matching the ones declared by the platform C++ library, making the structs more flexible and eliminating the need to have C++ code.

If that's too hard, even having the proper size rather than a 0-sized array field would be almost as good.

**Comment by dtolnay** [comment]
These types are incorrect to ever use by value in Rust because they rely on C++ move constructors to rewire internal pointers on move. It's intentional that you cannot hold them by value in Rust.

**Comment by kytans** [comment]
A precise layout is needed even if you don't need to be it around, e.g. to have a reference to a struct that includes a std::vector field.

Also, whether the C++ types depend on move constructors being called depends on the exact C++ library used; most likely std::vector doesn't, since it's usually implemented just like Rust's Vec..
