### ISSUE TITLE
Add support for method in shared enums

### ISSUE THREAD

**Issue by kraktus** [dtolnay/cxx#1154]
currently it's not possible to declare methods on shared enums, unlike on shared structs.

```rust
#[cxx::bridge]
mod ffi {
    pub enum Foo { Bar, Baz};
    extern "Rust" {
            fn foo(self: &Foo); // unsupported method receiver
    }
}
```

**Comment by dtolnay** [comment]
C++ does not support methods on enums. You'd need to go through the C++ committee for this.

**Comment by kraktus** [comment]
I see, thank you for the answer
