### ISSUE TITLE
Improvement of strange lint warnings

### ISSUE THREAD

**Issue by Enyium** [dtolnay/cxx#1162]
I have `#![warn(clippy::pedantic)]` in my crate's `lib.rs`. In CXX bridges, this can lead to warnings about things that are not my business. If you could please use `#[allow(clippy::pedantic)]` in the relevant, not all-encompassing locations, this would solve these warnings. If you aren't sure where exactly, here's concrete warnings I get:

- Without `#![allow(clippy::ptr_as_ptr)]` in my bridge, I get `` `as` casting between raw pointers without changing its mutability `` on non-`self` parameters in the `extern "C++"` block that have the pattern `&T` or `Pin<&mut T>`, where `T` is a C++ bridge type. See https://rust-lang.github.io/rust-clippy/master/index.html#ptr_as_ptr.
- Without `#![allow(clippy::expl_impl_clone_on_copy)]` in my bridge, I get `` you are implementing `Clone` explicitly on a `Copy` type `` in `enum`s that work together with an `extern "C++"` type of the same name (in [that](https://cxx.rs/shared.html#extern-enums) sense). See https://rust-lang.github.io/rust-clippy/master/index.html#expl_impl_clone_on_copy.

---

Not related to `#![warn(clippy::pedantic)]` is the following kind of warning: Without `#![allow(dead_code)]` in my bridge, I get `` associated constant `FOO_BAR` is never used `` on `enum`s. Is there a better `allow`able warning possible, something with "unused"? The worst is, I can't use `#[allow(dead_code)]` on the whole enum, but only on every single currently unused variant, which are many in that large `enum`. (Hence, I'm temporarily using it on the whole bridge, which works again.)

---

Related: #1061

**Comment by edward-shen** [comment]
The `clippy::use_self` lint also seems to be emitted when defining a shared `enum` type that has an existing c++ enum implementation:

Repro:

Rust side
```rust
#[cxx::bridge]
mod ffi {
    #[derive(Debug)]
    enum SomeErrorType {
        EMPTY,
    }

    unsafe extern "C++" {
        include!("mylibrary.h");
        type SomeErrorType;
    }
}
```

Cpp side
```cpp
enum class SomeErrorType : unsigned char {
  EMPTY,
};
```
