### ISSUE TITLE
Issue using a shared struct together with an extern C++-struct

### ISSUE THREAD

**Issue by Nick79919030** [dtolnay/cxx#1178]
Hello everyone!
I am trying to use a cxx shared struct together with an extern C++-struct, but this is the error message I receive:

`The following warnings were emitted during compilation:
warning: In file included from /home/.../crate/testbridge/src/Teststruct.hpp:2,
warning:                  from /home/.../testbridge/target/debug/build/testbridge-dc88e509b695cbaf/out/cxxbridge/sources/testbridge/src/lib.rs.cc:1:
warning: /home/.../testbridge/target/debug/build/testbridge-dc88e509b695cbaf/out/cxxbridge/include/testbridge/src/lib.rs.h:7:22: error: ‘Teststruct’ in namespace ‘::’ does not name a type
warning:     7 | using Teststruct = ::Teststruct;
warning:       |                      ^~~~~~~~~~
error: failed to run custom build command for `testbridge v0.1.0 (/home/.../testbridge)`
Caused by:
  process didn't exit successfully: `/home/.../testbridge/target/debug/build/testbridge-984fcd4d6e795e11/build-script-build` (exit status: 1)`

So, my question is, is it even possible to use a C++-struct alongside a shared struct with cxx?

// lib.rs

```
#[cxx::bridge]
mod ffi {
    struct SharedStruct {
        testvalue: u8,
    }
    unsafe extern "C++" {
        include!("testbridge/src/Teststruct.hpp");

        type Teststruct;
    }
}
```

// Teststruct.hpp

```
#pragma once
#include "testbridge/src/lib.rs.h"
#include <memory>

class Teststruct
{
public:
    SharedStruct Teststruct;
};
```

Thanks to everyone in advance! :)

**Comment by dtolnay** [comment]
You need to fix the import cycle between your two headers. They can't both `include` the other in C++.

**Comment by Nick79919030** [comment]
Hey dtolnay, thanks for the great advice!:) 
My Buddy and I solved the Issue now by using an extra crate where we defined our SharedStruct in another cxx::bridge and then later on defined our SharedStruct as a type back in our main cxx::bridge (crate).

Thanks again for the great help!
