### ISSUE TITLE
Support inner bridge mod

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cxx#119]
Currently we only find the #\[cxx::bridge\] invocation if it is at the top level of the Rust file passed as argument to the code generator. If it isn't at the top level, we fail with an error that looks like:

```console
cxxbridge: no #[cxx::bridge] module found
```

It would be good to also look for it inside of nested modules:

```rust
// lib.rs

pub fn ...

#[doc(hidden)]
mod details {
    #[cxx::bridge]
    mod ffi {
        ...
        ...
    }

    pub fn ...
}
```

**Comment by regexident** [comment]
I might be misinterpreting this issue, but whenever I put the `#[cxx::bridge]` anywhere but the crate root I still get 

```terminal
cxxbridge: no #[cxx::bridge] module found
```

### Reproduce

1. Open project `cxx/demo`
2. Add `pub mod bridge;` to `main.rs`, along with corresponding file `src/bridge.rs`
3. Move `#[cxx::bridge(namespace = "org::blobstore")] mod ffi { … }` from `main.rs` to `bridge.rs`
4. Mark `mod ffi` as `pub mod ffi`.
5. `cargo build`

### Module structure

```terminal
crate demo
└── pub mod bridge
    │   #[cxx::bridge(…)]
    └── pub mod ffi
```

### Error

```terminal
❯ cargo build
   Compiling demo v0.0.0 (/cxx/demo)
error: failed to run custom build command for `demo v0.0.0 (/cxx/demo)`

Caused by:
  process didn't exit successfully: `/cxx/target/debug/build/demo-02f344be574bf590/build-script-build` (exit code: 1)
  --- stdout
  cargo:CXXBRIDGE_PREFIX=demo
  cargo:CXXBRIDGE_DIR0=/.../cxx/target/debug/build/demo-9b77e4bc641295bf/out/cxxbridge/include
  cargo:CXXBRIDGE_DIR1=/.../cxx/target/debug/build/demo-9b77e4bc641295bf/out/cxxbridge/crate

  --- stderr
  cxxbridge: no #[cxx::bridge] module found
```

**Comment by dtolnay** [comment]
Probably your `cxx_build::bridge` call in build.rs is pointed to the wrong file.

**Comment by regexident** [comment]
Oh, so it needs to be within the **file** passed to `cxx_build::bridge`?

My understanding was that with #508 it now could be in any sub-module of the root module.

Makes sense. So I would do `cxx_build::bridge("src/bridge.rs")` then instead?

**Comment by dtolnay** [comment]
It can be within any submodule in the given file -- like in the comment at the top of this issue the bridge is the submodule `self::details::ffi` inside lib.rs.
