### ISSUE TITLE
Support for nested types

### ISSUE THREAD

**Issue by hfiguiere** [dtolnay/cxx#1198]
I have a C++ interface that is:

```C++
namespace a {
namespace b {

struct MyClass {
    enum class MyEnum {
        MY_VALUE = 42
    }
};

}
}
```

The cxx bridge look as follow:
```Rust
#[cxx::bridge(namespace = "a")]
mod ffi {
   #[namespace = "a::b"]
   enum MyEnum {
      #[cxx_name = "MY_VALUE"]
      MyValue,
   }
   #[namespace = "a::b"]
   unsafe extern C++ {
      type MyEnum;
   }   
}
```

And it doesn't work because `a::b::MyEnum` doesn't name a type.

I found no way to tell `cxx` that it is `a::b::MyClass::MyEnum`. Using `#[cxx_name = MyClass::MyEnum]` cause a `error[cxxbridge]: unexpected token`, and using `#[namespace = a::b::MyEnum]` cause `redeclared as different kind of entity` error in the C++ build.

**Comment by schreter** [comment]
As a workaround, you can create a wrapper header file with something like this:
```c++
#include <original header>

namespace a::b {
    using MyClassEnum = MyClass::MyEnum;
}
```

and then use `a::b::MyClassEnum` in the bridge (of course, `include!` the wrapper header, not the original). Since it's just an alias, it should work as expected.

**Comment by hfiguiere** [comment]
Thanks !

I don't know why I didn't think of this.

**Comment by dtolnay** [comment]
Supporting these in a more straightforward way is tracked already in #593.

**Comment by hfiguiere** [comment]
ah sorry I actually missed the original issue.
