### ISSUE TITLE
Minimum GLIBC version requirements

### ISSUE THREAD

**Issue by rbdm-qnt** [dtolnay/cxx#1199]
I'm trying to use CXX on a server which has Ubuntu 20 installed, and I can't upgrade it to Ubuntu 22 due to other requirements, so the maximum GLIBC version I can install is the 2.31. When trying to compile corrosion I'm getting this error:

../corrosion/cxxbridge_v1.0.92/bin/cxxbridge: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.33' not found (required by ../corrosion/cxxbridge_v1.0.92/bin/cxxbridge) 
../corrosion/cxxbridge_v1.0.92/bin/cxxbridge: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32' not found (required by ../corrosion/cxxbridge_v1.0.92/bin/cxxbridge)
../corrosion/cxxbridge_v1.0.92/bin/cxxbridge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ../corrosion/cxxbridge_v1.0.92/bin/cxxbridge)

What can I do about this? I thought maybe this could be an unnecessary requirement, or I could use an older version of the lib, and if so which one would be best?

**Comment by schreter** [comment]
Uhm, cxxbridge is compiled from sources. Seems like you have compiled it on newer OS and reuse it on older OS (?). Just recompile?

Are you using `cargo` for build or something else? `cargo` normally compiles everything it needs on-demand correctly for your machine.

**Comment by jschwe** [comment]
This issue was also opened downstream in Corrosion (https://github.com/corrosion-rs/corrosion/issues/366), where I closed it after not being able to reproduce (and receiving no further feedback).

**Comment by dtolnay** [comment]
Whatever is going on does not seem at all specific to cxx, so I am not going to be able to help debug this person's environment.
