### ISSUE TITLE
How would commctrl objects be used in CXX?

### ISSUE THREAD

**Issue by not-a-seagull** [dtolnay/cxx#12]
I am currently writing some Rust code that will be called by external C code. This C code will call a Rust function and pass in a `void *` that represents a [commctrl](https://docs.microsoft.com/en-us/windows/win32/api/_controls/index) window. After some processing, this Rust function will call a C++ function that displays a message box (note: I plan to use [wxWidgets](https://docs.wxwidgets.org/stable/group__group__funcmacro__dialog.html#ga193c64ed4802e379799cdb42de252647) to display this message box, among other things. Because of the way wxWidgets is programmed (inheritance), I cannot import the required function into Rust.)

Essentially, my use case is this, in terms of code.

`gui/about.h`:

```
void ShowMessageBox(void *parent, int otherData);
```

`gui/about.cpp`:

```
#include <wx/wx.h>

void ShowMessageBox(void *parent, int otherData) {
  wxDialog *dummy = new wxDialog();
  dummy->SetHWND(parent);

  wxString result;
  result.Printf( wxT("The result is %d."), otherData); 
  wxMessageBox(result, "Result", wxOK | wxICON_INFORMATION, dummy);
}
```

`src/lib.rs`:

```
use std::ffi::c_void;

#[cxx::bridge]
mod ffi {
  extern "C" {
    include!("gui/about.h");
    fn ShowMessageBox(parent: *const c_void, other_data: i32);
  }
}

#[no_mangle]
pub unsafe extern fn function_that_is_called_from_c(parent: *const c_void, other_data: i32) {
  // processing and such
  ffi::ShowMessageBox(parent, other_data);
}
```

[Considering that raw pointers probably won't be added to this crate](https://github.com/dtolnay/cxx/issues/9), how would a window handle be communicated across the Rust/C++ boundary?

**Comment by dtolnay** [comment]
You could use bindgen for those signatures, or you could put a struct around the commctrl window pointer and treat it as an opaque C type. (Separately I filed #13 to allow skipping the struct wrapper to treat void\* itself as the opaque C type.)

```cpp
// about.h

struct CommctrlWindow {
  void *p;
};

void ShowMessageBox(const CommctrlWindow &parent, int otherData);
```

```cpp
// about.cpp

#include "gui/about.h"
#include "src/lib.rs"

void ShowMessageBox(const CommctrlWindow &parent, int otherData) {
  void *p = parent.p;
  (void)p;
  (void)otherData;
}
```

```rust
// lib.rs

use cxx::UniquePtr;
use ffi::CommctrlWindow;

#[cxx::bridge]
mod ffi {
    extern "C" {
        include!("gui/about.h");

        type CommctrlWindow;
        fn ShowMessageBox(parent: &CommctrlWindow, other_data: i32);
    }

    extern "Rust" {
        fn function_called_from_c(
            parent: UniquePtr<CommctrlWindow>,
            other_data: i32,
        );
    }
}

fn function_called_from_c(parent: UniquePtr<CommctrlWindow>, other_data: i32) {
    // processing and such
    let parent = parent.as_ref().unwrap();
    ffi::ShowMessageBox(parent, other_data);
}
```

Note: make sure to pull in cxx 0.1.1 because 0.1.0 had a bug in passing UniquePtr as an extern "Rust" function argument (#14).
