### ISSUE TITLE
How to return string vector for rust to c++?

### ISSUE THREAD

**Issue by zeroxer** [dtolnay/cxx#1200]
I have tried this

- foo.rs
```rust
pub fn hello(vec: Pin<&mut CxxVector<CxxString>>) {
    vec.push(CxxString("Test"));
}
```

- main.cpp
```cpp
    vector<string> results;
    hello(results);

    for(auto& str: results) {
        cout << str << endl;
    }

```

**Comment by skydig** [comment]
@zeroxer I have same question, have you tried successed?

**Comment by dtolnay** [comment]
The code shared above seems like it works. I'm not sure if this was opened because it didn't work?

**Comment by skydig** [comment]
I use cxx 1.0.94

the line 
 vec.push(CxxString("Test"));

the compiler report:
cxx::cxx_vector::CxxVector
pub fn push(self: Pin<&mut Self>, value: T)
where
    T: ExternType<Kind = Trivial>,
Appends an element to the back of the vector.

Matches the behavior of C++ std::vector<T>::push_back.

type mismatch resolving `<CxxString as ExternType>::Kind == Trivial`
expected enum `Trivial`, found enum `cxx::kind::Opaque`rustcClick for full compiler diagnostic
cxx_vector.rs(166, 23): required by a bound in `CxxVector::<T>::push`

**Comment by dtolnay** [comment]
Ah I see -- you'd need to do the `push_back` from C++. Something like this:

```rust
// in Rust
let_cxx_string!(element = "Test");
ffi::vector_push_string(vec.as_mut(), element);
```

```rust
// in the FFI module
extern "C++" {
    fn vector_push_string(vec: Pin<&mut CxxVector<CxxString>>, element: Pin<&mut CxxString>);
}
```

```cpp
// in the C++ implementation
void vector_push_string(std::vector<std::string> &vec, std::string &element) {
  vec.emplace_back(std::move(element));
}
```

**Comment by skydig** [comment]
@dtolnay thanks，it works
