### ISSUE TITLE
Badly need incremental C++ builds

### ISSUE THREAD

**Issue by mlfarrell** [dtolnay/cxx#1237]
The bridge seems to recompile the entire C++ codebase every time it is invoked, even if only one file has been changed.  The "incremental" profile flag has no effect on behavior.

This is adding up to cost me over an hour per work day waiting on full rebuilds of our c++ lib

```
let mut bridge = cxx_build::bridges(&source_files).files(&cpp_files).cpp(true).clone();
//...

bridge.compile("lib");
```

**Comment by dtolnay** [comment]
Cargo's limited build.rs functionality has no way to handle this better. It sounds like you need to consider using a real multi-language build system, such as Buck2 or Bazel, which do not have this behavior.
