### ISSUE TITLE
follow the tutorial do a little test, undefined reference,why?

### ISSUE THREAD

**Issue by aohan237** [dtolnay/cxx#1238]
https://cxx.rs/tutorial.html

dirs：
include
src
Cargo.toml

here are the files：
include/test.h
"""
int detect();
"""
src/test.cc
"""
#include "cxx_demo/include/test.h"
int detect() {return 0 ;};
"""
src/build.rs
"""
fn main() {
    cxx_build::bridge("src/main.rs")
        .file("src/test.cc")
        .compile("demo");
}
"""
src/main.rs
"""
#[cxx::bridge]
mod ffi {
    unsafe extern "C++" {
        include!("cxx_demo/include/test.h");
        fn detect() -> i32;
    }
}

fn main() {
    let _client = ffi::detect();
}
"""

cargo build raise error note:
 main.rs:5: undefined reference to `cxxbridge1$detect

**Comment by dtolnay** [comment]
`src/build.rs` is the wrong location for a Cargo build script. It needs to be `build.rs` in the same directory that contains Cargo.toml. Or else you need to put `build = "src/build.rs"` into the Cargo.toml.

**Comment by aohan237** [comment]
thanks

**Comment by aohan237** [comment]
@dtolnay  from doc https://docs.rs/cxx-build/1.0.98/cxx_build/static.CFG.html#cfginclude_prefix
`The prefix at which C++ code from your crate as well as directly dependent crates can access the code generated during this build.

By default, the include_prefix is equal to the name of the current crate. That means if your crate is called demo and has Rust source files in a src/ directory and maybe some handwritten C++ header files in an include/ directory, then the current crate as well as downstream crates might include them as follows:

  // include one of the handwritten headers:
#include "demo/include/wow.h"

  // include a header generated from Rust cxx::bridge:
#include "demo/src/lib.rs.h"

By modifying CFG.include_prefix we can substitute a prefix that is different from the crate name if desired. Here we’ll change it to "path/to" which will make import paths take the form "path/to/include/wow.h" and "path/to/src/lib.rs.h".`

what is the path/to means? it is not a absolute path. i tried.
so. the path/to means the same path as the build.rs located in ?

what is i have a cpp in src like detect as above, but it includes an opencv4 for example, like located in dir : 
src/lib/opencv4
and other lib like
src/lib/thirdparty

how to include these libs? the tutorial has no example on this
