### ISSUE TITLE
[help] incorrect rust u8 to uint8_t

### ISSUE THREAD

**Issue by divflex** [dtolnay/cxx#1246]
I have a shared struct 

```rust
pub struct ABC {
  pub n: u8;
}
```

c++:

```c++
void echo(const Abc &abc)
        {
            std::cout << abc.n << std::endl;
        }
```

no matter what value n is , the  c++ side will always print 3

**Comment by nneesshh** [comment]
[test_echo_n.zip](https://github.com/dtolnay/cxx/files/12067730/test_echo_n.zip)

I print n with everything ok, what is you real code?
