### ISSUE TITLE
Emit with relative symlinks?

### ISSUE THREAD

**Issue by j-baker** [dtolnay/cxx#1250]
I'm using https://crane.dev to build a Cargo project with Nix. Crane has an elegant feature where it can precompile all dependencies in one build step (which is cached) so unless you change your dependencies, no recompile of dependencies is required. This drastically speeds up builds.

The approximate process by which it does this is:

```
cargo build
mv target $out
```

Unfortunately, cxx seems unique in our tech stack in that it creates absolute symlinks in its output, which end up like:

```
lrwxr-xr-x  1 root  wheel  189  1 Jan  1970 ./release/build/mycrate-461e0524ef218d12/out/cxxbridge/include/mycrate/src/lib.rs -> /private/tmp/nix-build-cargo-package-deps-0.0.1.drv-1/source/target/release/build/mycrate-461e0524ef218d12/out/cxxbridge/include/mycrate/src/lib.rs.h
```

Unfortunately, the tempdir is immediately deleted. I'm wondering if there's a reason other than simplicity that absolute symlinks are used here, and whether a PR might be accepted that adjusts them to being relative? At the moment I am resolving this problem by running `symlinks -rc $PWD` on the directory after the build has occurred, but this feels more fragile than fixing the source.

I _think_ that this would also have the effect of meaning that cxx builds are not broken after a move of the project directory, but am not 100% on how cache invalidation works.

**Comment by dtolnay** [comment]
I would be open to a PR that makes the symlinks relative.
