### ISSUE TITLE
Just a heads up: Comprehensive Rust will grow a CXX tutorial

### ISSUE THREAD

**Issue by mgeisler** [dtolnay/cxx#1280]
Hi @dtolnay! I maintain [Comprehensive Rust](https://google.github.io/comprehensive-rust/) and I just want to give you a heads up that we're adding a set of slides about CXX to it. We already teach using CXX in the course, but right now we simply [delegate to the excellent blobstore tutorial](https://google.github.io/comprehensive-rust/android/interoperability/cpp.html).

The plan is to present roughly the same material, but do it in slide form: https://github.com/google/comprehensive-rust/pull/1392.

We will copy some of the code from your tutorial to our `third_party/` directory. Please let me and @randomPoison know if you have any concerns with this!

**Comment by dtolnay** [comment]
Sounds good, please go ahead. Thank you for the notice.
