### ISSUE TITLE
How to pass binary string from Rust to C++?

### ISSUE THREAD

**Issue by beichen2012** [dtolnay/cxx#1291]
How to pass binary string (not valid utf-8 characters) from Rust to C++?

**Comment by moshimo2019** [comment]
Currently, it seems that there is no out-of-the-box API in cxx to pass OsString from Rust to  C++.
You need to convert it to String:
```rust
let os = OsString::new();
let s = unsafe { String::from_utf8_unchecked(os.into_encoded_bytes()) };
```
Anyway, it's fallible to convert an OsString (not valid utf-8) to String in Rust.
So you can directly pass `&[u8]` to C++ and then construct a std::string.

**Comment by beichen2012** [comment]
Thanks.
Finally, Implemented by passing Vec[u8] from Rust to C++.
