### ISSUE TITLE
Implement VectorElement for more types

### ISSUE THREAD

**Issue by adamchalmers** [dtolnay/cxx#1297]
# Background

I have an enum `EntityType`, which in Rust is

```rust
#[repr(u8)]
enum EntityType {
  Entity,
  Object,
  Path,
}
```

and in C++ is 

```c++
enum class EntityType : uint8_t
{
    Entity,
    Object,
    Path
};
```

The Rust type implements `cxx::ExternType` appropriately bridging these two.

# Problem

I cannot put this type into a CxxVector because `EntityType` does not implement [`cxx::VectorElement`](https://docs.rs/cxx/latest/cxx/vector/trait.VectorElement.html). I think I should be able to, though, because really it's just a u8 and that u8 does impl `VectorElement`.

# Possible solution

Allow users to implement VectorElement if it's an enum/newtype around some `T: VectorElement`.

# Workaround

Just use `CxxVector<u8>` and convert between u8 and `EntityType` where appropriate in either Rust or C++.

**Comment by dtolnay** [comment]
I think this is already supported. You need to use https://cxx.rs/extern-c++.html#explicit-shim-trait-impls.

```rust
impl CxxVector<EntityType> {}
```

in the same cxx::bridge that defines `EntityType`.

**Comment by adamchalmers** [comment]
So, what I actually have is closer to this:


```rust
pub mod cpp {

    #[namespace = "Enums"]
    unsafe extern "C++" {
        include!("enums.h");

        type _EntityType = kittycad_modeling_cmds::shared::EntityType;
    }

}
```

If I add `impl CxxVector<_EntityType> {}` I get 

```
error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
  --> bridge/src/engine.rs:71:5
   |
71 |     impl CxxVector<_EntityType> {}
   |     ^^^^^^^^^^^^^^^-----------
   |     |              |
   |     |              `EntityType` is not defined in the current crate
   |     impl doesn't use only types from inside the current crate
   |
   = note: define and implement a trait or new type instead

For more information about this error, try `rustc --explain E0117`.
```

Otherwise, if I try `impl CxxVector<kittycad_modeling_cmds::shared::EntityType> {}` I get 

```

  error[cxxbridge]: unsupported type
     ┌─ src/engine.rs:71:20
     │
  71 │     impl CxxVector<kittycad_modeling_cmds::shared::EntityType> {}
     │                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unsupported type
```

**Comment by dtolnay** [comment]
It needs to be in the same crate that defines `kittycad_modeling_cmds::shared::EntityType`, i.e. in kittycad_modeling_cmds. Just like a `Clone` impl or `Debug` impl or `ExternType` impl would also need to be in that crate.

**Comment by dtolnay** [comment]
```rust
unsafe extern "C++" {
    include!("enums.h");

    type _EntityType = crate::shared::EntityType;

    impl CxxVector<_EntityType> {}
}
```

**Comment by adamchalmers** [comment]
OK, I see, thanks. In this particular case it won't be possible, as the `kittycad_modeling_cmds` crate is open-source but our C++ code is closed-source. The workarounds will be enough in this case though, thanks. I'll open a PR to clarify the VectorElement docs.
