### ISSUE TITLE
cxx doesn't seem to support move self

### ISSUE THREAD

**Issue by boluoyu** [dtolnay/cxx#1310]
Have the following code：

```rust
struct NetClient;

 
impl NetClient {

   fn start_run(self) {
       ...
    }
}

#[cxx::bridge]
pub mod ffi_rust_cpp {

     extern "Rust" {
            type NetClient;
             fn start_run(self); //error: unsupported method receiver
    }
}


```
What should I do?I need your help.

**Comment by dtolnay** [comment]
C++ does not have any equivalent for moving `self` into a member function call. There is no such thing as by-value `this`. You need to not use that in methods that need to be called from C++.
