### ISSUE TITLE
Extern C++ Enums

### ISSUE THREAD

**Issue by djlalo08** [dtolnay/cxx#1340]
Is it possible to use an `extern C++` enum to call `extern C++` function?
```C++
//colors.cpp
enum Color {red, blue};

void printColor(Color c){
    std::cout << c << std::endl;
}
``` 

I'm imagining something like this:
```Rust
//main.rs
#[cxx::bridge]
mod ffi {
    extern unsafe "C++" {
        type Color;
        fn printColor(c: Color);
    }
}

fn main(){
    ffi::printColor(ffi::Color::red);
}
```

**Comment by dtolnay** [comment]
Yes, this is equivalent to https://github.com/dtolnay/cxx/issues/1332. You need to provide an ABI-compatible Rust definition of the type using `ExternType`.

**Comment by djlalo08** [comment]
Ah, I actually came across that issue in my search, but that example was going in the other direction (call a function that returns an enum, rather than takes one). I was able to replicate #1332 but haven't been able to to pass in an extern enum -- after Your response, my guess is I've just made a mistake somewhere...

In any case, thanks for responding, and for developing this awesome crate!

**Comment by mystchonky** [comment]
@djlalo08 did you figure out how to do this ? 
>  haven't been able to to pass in an extern enum -- after Your response, my guess is I've just made a mistake somewhere...
