### ISSUE TITLE
Feature Request: Add support for nested Vector types

### ISSUE THREAD

**Issue by IBims1NicerTobi** [dtolnay/cxx#1342]
It would be great if there was some way to pass a Vec<Vec<T>> from Rust to C++. This is currently not possible without applying some hack with a struct and a Vec inside that struct which is very annoying and leads to extra boilerplate code on the C++ side.
MWE:
```
#[cxx::bridge(namespace="test")]
mod ffi {
    extern "Rust" {
        fn test() -> Vec<Vec<f32>>;
    }
}
```

**Comment by mbrobbel** [comment]
https://github.com/dtolnay/cxx/issues/671
