### ISSUE TITLE
Consider mandating `extern "C++"` for C++ things

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cxx#137]
We currently accept both `extern "C"` and `extern "C++"` and treat them the same.

However with #4 we may end up wanting to translate the two languages somewhat differently, in particular mapping Rust references to pointers in C and references in C++.

We can't make this change in the near term because until recently Rustfmt would silently rewrite `extern "C++"` into `extern "Rust"` (https://github.com/rust-lang/rustfmt/issues/4086). 🤦🤦‍♀️🤦‍♂️

**Comment by adetaylor** [comment]
> Rustfmt would silently rewrite `extern "C++"` into `extern "Rust"`

If only it did that for more general C++ code.
