### ISSUE TITLE
Multiple `c_str` calls produce very large strings

### ISSUE THREAD

**Issue by sirandreww** [dtolnay/cxx#1406]
Here is the code for `c_str`, the vector is prolonged an a null terminator is added. Maybe this should only be done if it is not already null terminated.
```cpp
const char *String::c_str() noexcept {
  auto len = this->length();
  cxxbridge1$string$reserve_additional(this, 1);
  auto ptr = this->data();
  const_cast<char *>(ptr)[len] = '\0';
  return ptr;
}
```

**Comment by dtolnay** [comment]
Could you share some example code that demonstrates what you mean? Are you saying `string.capacity()` grows unboundedly?

**Comment by dtolnay** [comment]
As far as I can tell, this code is correct and does not produce large strings.
