### ISSUE TITLE
Split cxx crate into runtime and build.rs components

### ISSUE THREAD

**Issue by maurer** [dtolnay/cxx#144]
Right now, the cxx crate contains both runtime components (e.g. `cxx::unique_ptr`) and build time components (e.g. `cxx::gen`, `cxx::Build`).

This is negative because:
* For cross compilation builds, this requires that what should be build-only dependencies be supported on the target.
* This builds more functionality into the target binary than needed. If cxx is linked statically, there's a good chance most of this will be removed, but it will bloat in cases where it's linked dynamically.
* For homogenous build systems (bazel, buck, etc.) this requires them to pull in the `cc` and `link_cplusplus` crates to their source tree, which will never actually be used.

The two ways I see forwards here are:
* Split it using features. Users of homogenous build system, or who cared about binary size, etc. would be expected to disable a default feature to get a support-code-only version of the crate.
* Split it into separate crates, e.g. cxx-support and cxx-build, possibly keeping the main cxx crate as a wrapper that re-exports both.

Opinions?

**Comment by dtolnay** [comment]
We should split the crate. I'll try to move the build-only stuff to a `cxx-codegen` crate and keep only the runtime components in `cxx`.

**Comment by maurer** [comment]
Do you want to handle that yourself, or should I send up a PR? I had it temporarily split with a feature to get it working in my context.

**Comment by dtolnay** [comment]
I will take care of this one since I'll probably be picky about the directory layout. It sounds like you have a workaround for now? If so, I'll aim to get this done and published early next week.

**Comment by dtolnay** [comment]
Fixed in 0.3.0.
