### ISSUE TITLE
Unsafe inline C++

### ISSUE THREAD

**Issue by Serentty** [dtolnay/cxx#147]
In the past I've used the ``cpp`` crate, which has a similar goal of facilitating mixed Rust/C++ projects, but it takes the different approach of allowing inline C++ blocks in Rust code. However, it does not offer any kind of type checking like this project does, and it is very easy to make mistakes on side of the FFI boundary that lead to unsafety. It is also much less active than this project. I see a few advantages to supporting a similar style of inline C++ blocks.

1. They allow code which is connected in function to be placed together instead of divided according to language boundaries.
2. They allow C++ code which is only used once to be kept local to where it is used instead of put in a utility functions which can easily be called from elsewhere.
3. They greatly simplify the build process by allowing the programmer to simply add a single line to ``build.rs`` instead of having to list every file containing C++ code. In cases where new C++ code is being written as part of a project (such as for the purpose of calling C++ interfaces), it would be useful to let it share the same source tree as the Rust code, and have it just work with Cargo.
4. They explicitly use the ``unsafe`` keyword, which draws attention to the fact that the C++ code needs to be audited.

I understand that this is a fundamentally different approach, but I think both ways of integrating C++ code can be useful, and that they would benefit from sharing many of the same improvements.

**Comment by dtolnay** [comment]
I am familiar with the `cpp` crate and it's neat, but it is not something that I would like to pursue in this project.

It may be better to pursue the reverse, ask `cpp` if they'd like to support types from this crate in their system. That would be a really natural fit that allows manipulating Rust types easily from the nested C++ code. For example here is a hypothetical snippet with a Rust `Vec<T>` that gets manipulated using the API of this crate's `rust::Vec<T>` binding:

```rust
fn main() {
    let ref mut v = Vec::new();
    let r = cpp!([v as &mut Vec<i32>] {
        std::cout << "starting with " << v.size() << " elements\n";
        v.push_back(3);
        v.push_back(2);
        v.push_back(1);
    });
    println!("{:?}", v);
}
```

**Comment by Serentty** [comment]
Hm... that's certainly an idea. I appreciate how this project saves you from having to write function prototypes for Rust functions in C++. I wonder if something like that would be possible in ``cpp`` if it decided to integrate functionality from this crate.

**Comment by dtolnay** [comment]
I hope so!
