### ISSUE TITLE
Plugin interface question

### ISSUE THREAD

**Issue by scott-wilson** [dtolnay/cxx#163]
Hello,

First of all, thank you for this library. I've been planning on writing a wrapper for a 3d application's C++ library (Maya).

One thing that I'd like to do is also use cxx for writing plugins. Maya expects that the compiled library has a function that looks like this:

```cpp
MStatus initializePlugin(MObject plugin);
```

How would I be able to have that in my plugin? I was planning on having a file like plugin.cpp that holds that function, and then it passes the rest of the work to Rust or C++ (whatever is needed).

**Comment by dtolnay** [comment]
From skimming the Maya docs, MObject is a class declared in some Maya header, so only something that has parsed the header would know how to define a compatible signature. This crate doesn't parse C++ so it wouldn't be applicable there. For parsing the header you could either rely on a C++ compiler in the way that you described, or you could try feeding it to [bindgen](https://github.com/rust-lang/rust-bindgen) (probably with `--opaque-type MObject`) to get a compatible Rust type.

The C++ compiler way:

```cpp
#include <MObject.h>
#include <MStatus.h>
#include /*the CXX generated code*/

MStatus initializePlugin(MObject plugin) {
  auto status = rust_initialize_plugin(plugin);
  return static_cast<MStatus>(status);
}
```

```rust
#[cxx::bridge]
mod ffi {
    extern "C" {
        type MObject;
        fn /*any extern functions you need for manipulating the MObject*/
    }
    extern "Rust" {
        fn rust_initialize_plugin(plugin: &MObject) -> i32;
    }
}

pub fn rust_initialize_plugin(plugin: &ffi::MObject) -> i32 {
    /* ... */
}
```

The bindgen way:

```rust
#[path = /*the bindgen generated code*/]
mod maya_sys;

#[no_mangle]
pub unsafe extern "C" fn initializePlugin(plugin: maya_sys::MObject) -> maya_sys::MStatus {
    /* ... */
}

#[cxx::bridge]
mod ffi {
    extern "C" {
        type MObject;
        fn /*any extern functions you need for manipulating the MObject*/
    }
}
```

**Comment by dtolnay** [comment]
Based on [MObject Class Reference](http://help.autodesk.com/view/MAYAUL/2020/ENU/?guid=Maya_SDK_MERGED_cpp_ref_class_m_object_html) it looks like MObject might have a nontrivial constructor or destructor, so depending on the size of the private fields you might end up hitting https://github.com/rust-lang/rust-bindgen/issues/778 in the bindgen way where bindgen isn't able to make a compatible Rust signature. The C++ compiler way should definitely work though.

**Comment by scott-wilson** [comment]
Thank you! And that makes sense. I'm guessing my build process would be something like build the logic/Rust side, then build the plugin?

**Comment by dtolnay** [comment]
There shouldn't need to be a dependency between those in either approach. Depending on what build system you are using (e.g. in Bazel or Buck this would be the case) the logic/Rust side and the C++ side will build at the same time and you'll link them together at the end.

**Comment by scott-wilson** [comment]
Cool. I am hoping I can do this all in build.rs, but would probably fall back on CMake. Thanks again!
