### ISSUE TITLE
How to solve relocatable semantics between Rust and C++?

### ISSUE THREAD

**Issue by jclinton** [dtolnay/cxx#2]
Semantically, C++ types cannot be relocated because they may contain pointers to themselves or chains of objects that eventually point back to themselves. Rust assumes that all types can be relocated (e.g. by memcpy). Pin\<T\> can help with this problem when working with such FFI, but is there any way in which this crate can assist bridging these semantic differences?

**Comment by dtolnay** [comment]
In the CXX type system the only types that could contain internal pointers are the opaque C++ types. We don't allow opaque types to be passed across the FFI by value, only by reference or smart pointer. I think I would prefer to keep it that way; adding relocation behavior to Rust would need to be a separate project.
