### ISSUE TITLE
An option for cxxbridge to output the full cxxbridge.h header

### ISSUE THREAD

**Issue by sayrer** [dtolnay/cxx#20]
A typical Bazel setup will have something like this generated configuration:

```
alias(
    name = "cargo_bin_cxxbridge",
    actual = "//rust_bindings/cargo/vendor/cxxbridge-cmd-0.1.2:cargo_bin_cxxbridge",
)
```

This works fine for the two outputs that cxxbridge makes right now, but it would be nice for it to have an option to output the full `cxxbridge.h` header as well. Otherwise, it will require fishing around in vendor directories and adding extra Bazel rules to make the file visible. By using the alias for the command to produce the file, the reference will stay stable across upgrades, and `cxxbridge` can make internal changes without breaking builds.

I added this function to `include.rs`:

```
pub fn get_full_cxxbridge() -> &'static str {
	return HEADER
} 
```

and that seemed fine, but I wasn't sure what to do about the required `input` argument (I also couldn't test anything, because of #19). Here's a strawman:

```
     /// Emit header with declarations only
     #[structopt(long)]
     header: bool,
+
+    /// Emit full cxxbridge header
+    #[structopt(long)]
+    cxxbridge: bool,
+
 }
 
 fn main() {
     let opt = Opt::from_args();
+    if opt.cxxbridge {
+        let _ = io::stdout().lock().write_all(gen::include::get_full_cxxbridge().as_ref());
+        return;
+    }
     let gen = if opt.header {
         gen::do_generate_header
     } else {
```

which works if I call it with a dummy input file:

```
cargo run -- foo.rs --cxxbridge
```

**Comment by dtolnay** [comment]
Seems reasonable! Ideally I think `cxxbridge --header` (without a Rust source filepath) would emit the cxxbridge.h header.

**Comment by sayrer** [comment]
Yeah, I tried that but it complains about a missing input file. I couldn't figure out how to make StructOpt treat input as optional (I did read the docs).

**Comment by dtolnay** [comment]
I'm not that familiar with structopt either but my expectation would be that:

```diff
- input: PathBuf,
+ input: Option<PathBuf>,
```

makes it optional.

**Comment by sayrer** [comment]
OK, I'll try that. The docs are a bit confusing, since there are a couple "Option" synonyms.
