### ISSUE TITLE
Cannot `#include gen.rs.h` reliably when building with cargo due to dynamic out location

### ISSUE THREAD

**Issue by stoically** [dtolnay/cxx#213]
Thanks for cxx!

It seems that the location of the generated bridge files varies based on the method with which the crate is added as dependency. E.g. in the crate [keytar](https://github.com/stoically/keytar-rs/tree/a0d5ec84940a2355a4a820ad94faa4934370b65b) I've used [`#include "src/lib.rs.h"`](https://github.com/stoically/keytar-rs/blob/a0d5ec84940a2355a4a820ad94faa4934370b65b/src/lib.cc#L2), which works fine while working directly in the crate, since the `rs.h` file ends up in `TARGET_DIR/cxxbridge/src/lib.rs.h`. When adding the crate as `dependency` (ends up in `TARGET_DIR/cxxbridge/.cargo/..`) or including it via `path` (ends up in nested paths depending on the local directory name), the out location changes in unpredictable ways, which makes it hard (impossible?) to reliably `#include` it.

My naive approach to fix this would be to always write the given include path as-is to the `OUT_DIR` and make it an requirement to include that (or automatically include it as part of `cxx_build::bridge`).

Maybe I'm missing something obvious and it is possible to reliably define `#include`s for cargo, in which case I'd appreciate pointers. Thanks!

**Comment by dtolnay** [comment]
Fixed in 0.4.0 -- the import paths will now always be crate name + local path within crate, e.g. `#include "my-crate/src/lib.rs.h"` where `my-crate` is the crate name and `"src/lib.rs"` was the path passed to the cxx_build::bridge code generator.
