### ISSUE TITLE
Minor: better error message when missing "extern crate cxx"

### ISSUE THREAD

**Issue by sayrer** [dtolnay/cxx#215]
I forgot this line, but everything worked until I added a `Vec<T>`. At that point, I got E0433 for type `T`, but it showed the line in the source file. The compiler helpfully said "maybe missing crate cxx?" but it took me forever to figure out what that meant, since `T` is of course not in `cxx`.

Maybe this omission could be detected by `cxx`.

**Comment by dtolnay** [comment]
Is this in 2015 edition code? Otherwise `extern crate cxx` should never be necessary.

Can you share the source code that reproduces this?

**Comment by sayrer** [comment]
That was the problem. I was adding an FFI layer to old code.
