### ISSUE TITLE
Writing a binding to a C++ shared library

### ISSUE THREAD

**Issue by alexxbb** [dtolnay/cxx#223]
![Drawing](https://user-images.githubusercontent.com/10694389/85234712-36a58300-b3c4-11ea-8885-54b75d67d53f.png)

From what I found it seems like `cc::Build` doesn't support building a shared library, while with cxx crate its a must have feature. Shouldn't cxx_build provide a way to dynamically link a wrapper to a shared library? Or am I missing something obvious? Thanks!

**Comment by alexxbb** [comment]
I shouldn't rush with creating an issue, it turns out the linking is done like so:

```rust
fn main() {
    cxx_build::bridge("src/lib.rs")  // returns a cc::Build
        .file("cpp/wrap/wrap.cpp")
        .include("cpp/lib")
        .include(".")
        .flag("-std=c++14")
        .compile("cpp-wrap");

    println!("cargo:rustc-link-search=/path/to/library");
    println!("cargo:rustc-link-lib=spref");
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=cpp/wrap/wrap.h");
    println!("cargo:rerun-if-changed=cpp/wrap/wrap.cpp");
}
```

**Comment by ssh352** [comment]
> I shouldn't rush with creating an issue, it turns out the linking is done like so:
> 
> ```rust
> fn main() {
>     cxx_build::bridge("src/lib.rs")  // returns a cc::Build
>         .file("cpp/wrap/wrap.cpp")
>         .include("cpp/lib")
>         .include(".")
>         .flag("-std=c++14")
>         .compile("cpp-wrap");
> 
>     println!("cargo:rustc-link-search=/path/to/foo");
>     println!("cargo:rustc-link-lib=foo");
>     println!("cargo:rerun-if-changed=src/lib.rs");
>     println!("cargo:rerun-if-changed=cpp/wrap/wrap.h");
>     println!("cargo:rerun-if-changed=cpp/wrap/wrap.cpp");
> }
> ```

Run into the same issue, need to link to c++ shared lib with CXX. Is it possible you share a the runnable example via a git repo? What's the purpose of the wrap.h and wrap.cpp? As I understand, cc crate only compiles to libcxx-wrapper.a Thanks!

**Comment by alexxbb** [comment]
> > I shouldn't rush with creating an issue, it turns out the linking is done like so:
> > 
> > ```rust
> > fn main() {
> >     cxx_build::bridge("src/lib.rs")  // returns a cc::Build
> >         .file("cpp/wrap/wrap.cpp")
> >         .include("cpp/lib")
> >         .include(".")
> >         .flag("-std=c++14")
> >         .compile("cpp-wrap");
> > 
> >     println!("cargo:rustc-link-search=/path/to/foo");
> >     println!("cargo:rustc-link-lib=foo");
> >     println!("cargo:rerun-if-changed=src/lib.rs");
> >     println!("cargo:rerun-if-changed=cpp/wrap/wrap.h");
> >     println!("cargo:rerun-if-changed=cpp/wrap/wrap.cpp");
> > }
> > ```
> 
> Run into the same issue, need to link to c++ shared lib with CXX. Is it possible you share a the runnable example via a git repo? What's the purpose of the wrap.h and wrap.cpp? As I understand, cc crate only compiles to libcxx-wrapper.a Thanks!
> 
> 
> 

Sorry I don't have access to that code anymore, it was at my previous job. IIRC, wrap.h and wrap.cpp is where you define the bridge, e.g. C++ functions that you call from Rust.

**Comment by ssh352** [comment]
> > > I shouldn't rush with creating an issue, it turns out the linking is done like so:
> > > ```
> > > fn main() {
> > >     cxx_build::bridge("src/lib.rs")  // returns a cc::Build
> > >         .file("cpp/wrap/wrap.cpp")
> > >         .include("cpp/lib")
> > >         .include(".")
> > >         .flag("-std=c++14")
> > >         .compile("cpp-wrap");
> > > 
> > >     println!("cargo:rustc-link-search=/path/to/foo");
> > >     println!("cargo:rustc-link-lib=foo");
> > >     println!("cargo:rerun-if-changed=src/lib.rs");
> > >     println!("cargo:rerun-if-changed=cpp/wrap/wrap.h");
> > >     println!("cargo:rerun-if-changed=cpp/wrap/wrap.cpp");
> > > }
> > > ```
> > 
> > 
> > Run into the same issue, need to link to c++ shared lib with CXX. Is it possible you share a the runnable example via a git repo? What's the purpose of the wrap.h and wrap.cpp? As I understand, cc crate only compiles to libcxx-wrapper.a Thanks!
> 
> Sorry I don't have access to that code anymore, it was at my previous job. IIRC, wrap.h and wrap.cpp is where you define the bridge, e.g. C++ functions that you call from Rust.

Thanks, it is still helpful
