### ISSUE TITLE
rust::Slice::begin() and ::end()

### ISSUE THREAD

**Issue by tomjakubowski** [dtolnay/cxx#240]
It's very convenient on the C++ side that `rust::Vec` exposes `begin()`/`end()` member functions returning iterators. I may be missing something, but it seems like it would be equally possible and just as valuable for `rust::Slice`  to have similar methods which return its own iterators.

**Comment by dtolnay** [comment]
Absolutely. :) The entire API in our C++ bindings of Rust types is extremely bare bones right now and could use some love. Even basic things like `rust::Vec<T>::operator[]` isn't present yet (#149).

I don't suppose you would be interested in helping out with a PR?

**Comment by dtolnay** [comment]
Implemented in #516, released in cxx 1.0.5.
