### ISSUE TITLE
Pass Rust shared struct with vec member

### ISSUE THREAD

**Issue by happydpc** [dtolnay/cxx#261]
I am wondering how to set vertices vector array in c++ function. "rust::cxxbridge03::Vec" doesn't have push_back function.

```rust
	struct Vertex
    {
        position: Vec3,
        normal: Vec3,
    }
    struct Model
    {
        vertices: Vec<Vertex>,
    }
    extern "C" {
        include!("model/cpp/ExternModelInterface.h");
        pub fn importModel(file_path: &str) -> UniquePtr<Model>;
	}

```

**Comment by sayrer** [comment]
The C++ API for rust::Vec isn't done yet. See #149.

**Comment by dtolnay** [comment]
Yeah push_back is tracked as part of #149. For now you'd need to work around by exposing your own vector push function from Rust to C++.

In the Rust module:

```rust
#[cxx::bridge]
mod ffi {
    ...

    extern "Rust" {
        fn push_vertex(vec: &mut Vec<Vertex>, vertex: Vertex);
    }
}

fn push_vertex(vec: &mut Vec<ffi::Vertex>, vertex: ffi::Vertex) {
    vec.push(vertex);
}
```

In a header file:

```cpp
#pragma once
#include "rust/cxx.h"
#include <memory>

struct Model;

std::unique_ptr<Model> importModel(rust::Str file_path);
```

In a source file:

```cpp
#include "path/to/header.h"
#include "path/to/rust/src/lib.rs.h"

std::unique_ptr<Model> importModel(rust::Str file_path) {
  Vec3 position, normal;

  rust::Vec<Vertex> vertices;
  push_vertex(vertices, Vertex{position, normal});  // etc
  return std::make_unique<Model>(Model{std::move(vertices)});
}

```

Make sure you are using at least cxx 0.3.5 because &amp;mut Vec may not compile on older ones (#263).

**Comment by happydpc** [comment]
Oh, thank you for your detail solution, cxx is very easy to use.

**Comment by dtolnay** [comment]
I'll go ahead and close this in favor of tracking the push_back API at #149.

**Comment by dtolnay** [comment]
Update: cxx 0.5.9 now provides push_back for `rust::Vec`.

https://github.com/dtolnay/cxx/blob/4ab117115718908768df8366ac130bbbb3478331/include/cxx.h#L180-L184
