### ISSUE TITLE
Operator overloading

### ISSUE THREAD

**Issue by Volker-Weissmann** [dtolnay/cxx#264]
Hello,
Both C++ and Rust support operator overloading. It would be nice if you could call a C++ overloaded operator in rust.

Example based on the demo:
If one adds the following demo.cc:
```c++
void ThingC::operator+=(const ThingC &t) {
    appname += t.appname;
}
```
It would be nice if the following would work:
```rust
let mut x = ffi::make_demo("demo of cxx::bridge");
let y = ffi::make_demo("other text");
x += y;
```

**Comment by dtolnay** [comment]
Absolutely -- this is tracked already as part of #109.
