### ISSUE TITLE
How to deal with a function that returns a pointer to an opaque type?

### ISSUE THREAD

**Issue by laptou** [dtolnay/cxx#283]
I have a C++ program that relies on a C++ library; I am trying to port the C++ program to Rust. The library contains the following method:

```c++
class socc_examples_fixture {
public :
    // ...

    template <typename T>
    SDIDevicePropInfoDataset* wait_for_IsEnable(uint16_t code, T expect, int count=1000){
        // ...
    }
};
```

I don't care about the return value. In the C++ program I am porting, it is used like this:
```c++
fixture.wait_for_IsEnable(0xD6E2, 0x01);
```

However, I can't figure out how to bind this method with `cxx`. Here's what I tried:

```rust
#[cxx::bridge]
mod ffi {
     extern "C" {
        type socc_examples_fixture;

        fn wait_for_IsEnable(
            self: &mut socc_examples_fixture,
            code: u16,
            expect: u16,
            retry_count: i32,
        ) -> ();
     }
}
```
```rust
#[cxx::bridge]
mod ffi {
     extern "C" {
        type socc_examples_fixture;
        type SDIDevicePropInfoDataset;

        fn wait_for_IsEnable(
            self: &mut socc_examples_fixture,
            code: u16,
            expect: u16,
            retry_count: i32,
        ) -> *const SDIDevicePropInfoDataset;
     }
}
```
```rust
#[cxx::bridge]
mod ffi {
     extern "C" {
        type socc_examples_fixture;
        type SDIDevicePropInfoDataset;

        fn wait_for_IsEnable(
            self: &mut socc_examples_fixture,
            code: u16,
            expect: u16,
            retry_count: i32,
        ) -> &SDIDevicePropInfoDataset;
     }
}
```

None of these work. How can I bind to this method?

**Edit:** I worked around this by just changing the return type of this method to `void` in C++ and deleting the `return` statements, but that does not feel ideal. It won't be easy to `unique_ptr<>` this problem either, because the pointers this function returns are pointers to elements in a map.

**Comment by dtolnay** [comment]
I am very interested in supporting pointer types (and it's not a complicated feature) but it just hasn't been implemented yet. This is tracked in #164.

For now you could bind such a function by adding an `include!` which casts the return value to size_t:

```cpp
size_t casted_wait_for_IsEnable(
    socc_examples_fixture& self,
    uint16_t code,
    uint16_t expect,
    int32_t retry_count) {
  return size_t(self.wait_for_IsEnable(code, expect, retry_count));
}
```

and then cast the `usize` back to `*mut SDIDevicePropInfoDataset` in Rust.

**Comment by laptou** [comment]
Cool, thank you!

**Comment by dtolnay** [comment]
Closing in favor of the main issue tracking pointer support: #164.
