### ISSUE TITLE
Nested structs lead to incomplete type error

### ISSUE THREAD

**Issue by Timmmm** [dtolnay/cxx#292]
If I put this in my `mod ffi`:

    struct A {
        b: B,
    }
    struct B {
        c: i32,
    }

I get this error during compilation:

```
warning: /.../lib.rs.cc:255:5: error: field has incomplete type 'org::example::B'
warning:   B b;
warning:     ^
warning: /.../lib.rs.cc:225:8: note: forward declaration of 'org::example::B'
warning: struct B;
warning:        ^
warning: 1 error generated.
```

If I change it to `b: Box<B>` it works fine.

**Comment by dtolnay** [comment]
We'll want to implement a topological sort for data structures to fix this. The current implementation in cxx::bridge for shared structs is really basic, it just forward declares them all in original order and then defines them all in original order.

```cpp
struct A;
struct B;

struct A final {
  B b;
};

struct B final {
  int32_t c;
};
```

That's fine if forward references are boxed (as you noticed) or if the structs are topologically ordered already. (So a workaround for you is to put B before A in the cxx::bridge source file.)

**Comment by dtolnay** [comment]
Marking <kbd>help wanted</kbd>. A correct topological sort implementation here should handle translating this:

```rust
struct X { y: Y }
struct Y { z: UniquePtr<Z> }
struct Z { x: X }
```

into this:

```cpp
struct Z;

struct Y final { std::unique_ptr<Z> z; };
struct X final { Y y; };
struct Z final { X x; };
```
