### ISSUE TITLE
Vector of strings?

### ISSUE THREAD

**Issue by alexxbb** [dtolnay/cxx#296]
```rust
pub fn get_names() -> UniquePtr<CxxVector<CxxString>>;
```
Errors out with `CxxVector<CxxString>` - unsupported vector target type.

Am I missing something obvious here?

**Comment by dtolnay** [comment]
This was implemented a while ago in 0.3.6. It sounds like you are using a version older than that. You need to update cxx-build (or cxxbridge-cmd, depending on which one is used by your build system).

**Comment by alexxbb** [comment]
Yes, switched to 0.4 and now it works. Thank you!
