### ISSUE TITLE
Add continuous integration build that uses Bazel

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cxx#30]

**Comment by sayrer** [comment]
I've started working on this. I think the best example would use cargo raze to install cxx itself (using a path to the root of the repo), and build a small crate that uses cxx and a small rust dependency (like num_cpus). I have this script generating a bunch of Bazel build files now:

```
#!/usr/bin/env bash

cargo generate-lockfile && \
cargo vendor --versioned-dirs --locked && \
cargo raze && \
cat >> $(find vendor/cxx-* -name "BUILD.bazel") <<- EOM

cc_library(
 name="cxx_cc_library",
 hdrs=glob(["include/**/*.h"]),
 srcs=glob(["src/**/*.cc"]),
)

EOM
```

**Comment by dtolnay** [comment]
Looks good! I think you may also need to add a dep from the cxx crate rust_library target on the cxx_cc_library target. I am open to accepting whatever metadata needs to go in our Cargo.toml to get cargo-raze to make sense of that dependency edge.

**Comment by sayrer** [comment]
In my code, I'm only doing C++ to Rust, where you need to create a wrapper cc_library anyway, in Bazel. I just put the generated library there.

https://github.com/bazelbuild/rules_rust/tree/master/examples/ffi

I'll do a Rust to C++ example as well, though.
