### ISSUE TITLE
Trait impls needed for type aliases

### ISSUE THREAD

**Issue by adetaylor** [dtolnay/cxx#312]
Commit 2b821e60e00c139dd8a2db829c0bf5a052ebd875 disabled type aliases for non-local types.

This causes problems with this sort of code:

```rust
mod ffi {
    unsafe impl cxx::ExternType for bindgen::Bob {
        type Id = cxx::type_id!("Bob");
    }
    mod bindgen {
        #[repr(C)]
        pub struct Bob {
            pub a: u32,
            pub b: u32,
        }
    }
    #[cxx::bridge]
    pub mod cxxbridge {
        extern "C" {
            include!("input.h");
            pub fn take_bob(a: UniquePtr<Bob>) -> u32;
            type Bob = super::bindgen::Bob;
        }
    }
}

```

because of course

```
error[E0277]: the trait bound `ffi::bindgen::Bob: cxx::private::UniquePtrTarget` is not satisfied
  --> demo/src/main.rs:32:32
   |
32 |             pub fn take_bob(a: UniquePtr<Bob>) -> u32;
   |                                ^^^^^^^^^^^^^^ the trait `cxx::private::UniquePtrTarget` is not implemented for `ffi::bindgen::Bob`
   | 
  ::: /Users/adetaylor/dev/cxx/src/unique_ptr.rs:14:8
   |
14 |     T: UniquePtrTarget,
   |        --------------- required by this bound in `cxx::UniquePtr`
```

(Context: previously my https://github.com/google/autocxx experiments rewrote the bindgen output to generate a self-contained `cxx::bridge`, but I believe the _better_ thing is to have lots of `ExternType`s pointing from the `cxx::bridge` to the bindgen output, so I'm trying to make that work. This may be the first of several issues as I dig into it.)

I'm eager to raise a PR to fix this but I can't see the easiest way. Given the context of 2b821e60e00c139dd8a2db829c0bf5a052ebd875, I assume some badness occurs if we generate trait impls for aliases _to types in other `cxx::bridge` blocks_. Is that the case? If so, I've a feeling we can't distinguish this case versus the type-defined-entirely-outside-cxxbridge case we've got here, and we might need some new syntax. Thoughts?

**Comment by dtolnay** [comment]
> I assume some badness occurs if we generate trait impls for aliases *to types in other `cxx::bridge` blocks*. Is that the case?

Yes this is the reason. You end up with multiple conflicting impls on the same type with no way to turn it off.

I think what I would prefer is for a module to be able to explicitly request certain impls to be instantiated. We would still keep our current implicit impls for convenience in all the cases where a particular impl is "obviously needed".

```rust
#[cxx::bridge]
mod ffi {
    extern "C++" {
        type Bob = super::bindgen::Bob;
    }

    impl UniquePtr<Bob> {}
}
```
