### ISSUE TITLE
Demo: Use same C++ standard as cxxbridge

### ISSUE THREAD

**Issue by roligugus** [dtolnay/cxx#323]
The demo code is currently set up to set the C++ standard by setting it in build.rs a la

```
    cxx_build::bridge("src/main.rs")
        .file("src/demo.cc")
        .flag_if_supported("-std=c++14")
        .compile("cxxbridge-demo");
```

However, cxx.h|cc are compiled with the CXX crate feature settings, i.e. cxxbridge_flags::STD. ffi tests already use the feature flag. 

We shall align the demo's build.rs to use cxxbridge_flags::STD so that we only have to declare the feature in demo's Cargo.toml.

While we're at it, it would be great to not having to set `flag_if_supported(cxxbridge_flags::STD)` when using cxx_build. cxx_build could directly set the feature flags. This makes the cxx_build usage less error-prone for cargo-based builds as it automatically ensures that custom FFI code and cxx.h|cc is compiled with the same features. Especially once we add C++17 features such as string_view support, or any other potential future feature such as absl, folly, or gsl support.

This is not an issue for bazel or buck builds.

Pull request incoming.

**Comment by roligugus** [comment]
@dtolnay Just to double check. Was expecting to see this issue closed with "not at this time" due to the outcome of PR #324.

Oversight, or would you like a pull request that does the change in demo's build.rs to?
```
 cxx_build::bridge("src/main.rs")
        .file("src/demo.cc")
        .flag_if_supported(cxxbridge_flags::STD)
        .compile("cxxbridge-demo");
```

**Comment by dtolnay** [comment]
I would prefer not to do this at this time, so I'll go ahead and close the issue. Thanks anyway!
