### ISSUE TITLE
Example for returning rust::Vec<uint8_t>

### ISSUE THREAD

**Issue by thomasantony** [dtolnay/cxx#344]
I cannot find an example for initializing a rust::Vec<uint8_t> in C++ and then return it to rust code. The only test I found is unimplemented. I tried passing std::vector, const uint8_t* etc. to the constructor and they don't seem to exist. Is this feature incomplete?

**Comment by dtolnay** [comment]
Vec's C++ API is mostly unimplemented (#149). The only constructor currently is a default constructor. See the API in [include/cxx.h](https://github.com/dtolnay/cxx/blob/4396abfafc69d5fe65fb10a5393a001d700a5043/include/cxx.h#L165).

You could either send a PR to fill out the API or follow the workaround in https://github.com/dtolnay/cxx/issues/261#issuecomment-682140987.

**Comment by dtolnay** [comment]
As of cxx 1.0.8, we now expose a fairly typical collection API on rust::Vec, including push_back, emplace_back, and an initializer_list constructor. https://cxx.rs/binding/vec.html

#### Using push_back:

```cpp
rust::Vec<uint8_t> vec;
vec.push_back(2);
vec.push_back(0);
```

#### Using initializer_list:

```cpp
rust::Vec<uint8_t> vec = {2, 0, 2, 0};
```

Some examples from the test suite:

https://github.com/dtolnay/cxx/blob/0b933debac0fb7b20e70e075257d6555de0e57ec/tests/ffi/tests.cc#L135

https://github.com/dtolnay/cxx/blob/0b933debac0fb7b20e70e075257d6555de0e57ec/tests/ffi/tests.cc#L149-L151
