### ISSUE TITLE
Help with running demo from a git clone on Windows

### ISSUE THREAD

**Issue by foroughmajidi** [dtolnay/cxx#355]
I want to run demo but I got this error why?
please tell me how to solve this?
![Untitled](https://user-images.githubusercontent.com/51900859/95656281-1d167b80-0b1a-11eb-8ffc-8346051a8591.png)

**Comment by dtolnay** [comment]
You will need to follow one of the two solutions written in the error message. Delete the `cxx` directory and re-clone from GitHub with one of those fixes.

**Comment by foroughmajidi** [comment]
thanks for your response 
I did it at first I run 
for example in c:\sample gitbash here and then 
git config  - - global core.symlinks true 
finally 
git clone cxx repository

**Comment by dtolnay** [comment]
In general you wouldn't need either of those things (symlink enabled, and cargo run) when using cxx as a library, only for running that demo out of a local clone of git repository.
