### ISSUE TITLE
 Git unable to create symlink on Windows: permission denied

### ISSUE THREAD

**Issue by foroughmajidi** [dtolnay/cxx#357]
refer to Help with running demo from a git clone on Windows #355 
If I use this command git clone -c core.symlinks=true https://github.com/dtolnay/cxx.git
I got this 
![Untitled1](https://user-images.githubusercontent.com/51900859/95671460-53004200-0ba4-11eb-812c-1aeb43939cff.png)

and again I got this error

![Untitled2](https://user-images.githubusercontent.com/51900859/95671462-598eb980-0ba4-11eb-91a4-b6f973c8dad1.png)

**Comment by dtolnay** [comment]
I tried to add a more specific error in #358. Could you try building again from the newest commit on master and see if that was it, and if the steps in the new message fix it?

**Comment by david-cattermole** [comment]
Hello @dtolnay,

I'm not sure about @foroughmajidi, and I have never triggered the exact same problem, however I can confirm your new message correctly shows up (using the latest master commit) on Windows 10 when Symlinks and "Developer Mode" are turned on.

Thanks,
David C

**Comment by dtolnay** [comment]
Thanks for confirming! It's tricky to test these things without access to a physical Windows machine.

**Comment by dlongz** [comment]
I was also getting the "Error: unable to create symlink <file> : Permission denied."

It was resolved on my Windows 10 by turning on Developer mode.

<img width="304" alt="image" src="https://user-images.githubusercontent.com/30818298/201424837-7ea8e6ca-3dcf-4fca-aa73-3e67cf3ffc78.png">

I hope this helps!
