### ISSUE TITLE
ExternType fails static assert because the C++ type has a copy constructor

### ISSUE THREAD

**Issue by scott-wilson** [dtolnay/cxx#365]
Hello!

I'm creating a wrapper for OpenImageIO, and I'm running into an issue where I can't pass the static check https://github.com/dtolnay/cxx/blob/743caa283ced87d021e67c65ced1860fe0a11ecc/gen/src/write.rs#L436 because of this copy constructor https://github.com/OpenImageIO/oiio/blob/665c634b12ea8bc206e7a5dd9475cffa974e8522/src/include/OpenImageIO/typedesc.h#L165.

I could be wrong, but it it looks like this should pass, so this may be a case where removing the static check may be okay, however, having this in the first place did stop me to make sure I wasn't being a complete idiot and brought me to where we are now.

So, I have two main questions:

1. Is this static assert correct, and I have to wrap this in a unique pointer (or some option C)?
2. If this static assert can go away, then are we able to do this in a way where we can say "I'm absolutely sure that this type is okay to use" and still keep the static checks in place? Or, would it be on me in my c++ wrapper side to make sure the static asserts are in place?

**Comment by adetaylor** [comment]
I think #359 is the proposal to provide just the sort of override you need.

**Comment by scott-wilson** [comment]
Ack. That's what happens when you post before really looking at the issues. I'll close this thread.
