### ISSUE TITLE
LTO template?

### ISSUE THREAD

**Issue by XiangpengHao** [dtolnay/cxx#371]
It's natural for us to consider supporting cross-language LTO (linking time optimization) out of the box, LTO is extremely helpful when you have a bunch of small functions in hotpath.

Right now, it's not easy becuase https://github.com/rust-lang/rust/issues/60059, https://github.com/rust-lang/rust/issues/56371

Firefox enabled LTO last year with nontrivial efforts http://blog.llvm.org/2019/09/closing-gap-cross-language-lto-between.html

**Comment by XiangpengHao** [comment]
After some struggling, I made a minimal viable LTO setup with CMake here: https://github.com/XiangpengHao/cxx-cmake-example

This requires the system LLVM version to match with the rust LLVM version, for rust-1.49 it should be LLVM11.

**Comment by adetaylor** [comment]
Thanks a ton for doing this. I'm exactly your target audience: someone who really wants to use cross-language LTO with cxx but hadn't spared the time to figure out exactly the steps required. Cheers!

**Comment by dtolnay** [comment]
This is now linked from https://cxx.rs/build/cmake.html.
