### ISSUE TITLE
Set up C++ linter or static analysis in CI

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cxx#390]
I haven't done a C++ project before --- is there a good linter or static analyzer that we should be running on [include/cxx.h](https://github.com/dtolnay/cxx/blob/master/include/cxx.h) and [src/cxx.cc](https://github.com/dtolnay/cxx/blob/master/src/cxx.cc) in the GitHub Actions jobs?

**Comment by iulianR** [comment]
I'd argue that [clang-tidy](https://clang.llvm.org/extra/clang-tidy/) is one of the more up-to-date/complete/modern ones.

A set of [checks](https://clang.llvm.org/extra/clang-tidy/checks/list.html) also need to be enabled. The default ones probably are not enough. I recommend at least `modernize-*`, `clang-analyzer-*`and `cppcoreguidelines-*`.

I can have a look if you think clang-tidy is ok.

**Comment by dtolnay** [comment]
That would be great!
