### ISSUE TITLE
Decide on semantics of #[namespace = "..."]

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cxx#416]
Which of the following does this mean?

```rust
#[cxx::bridge(namespace = "n")]
mod ffi {
    extern "C++" {
        fn f();
    }
}
```

- A:　**"`f()` as if resolved inside of `::n`"**
- B:　**"precisely `::n::f()`"**

I realized when upgrading a nonpublic codebase from cxx 0.5.2 to 0.5.3 that we had unintentionally broken some code with https://github.com/dtolnay/cxx/pull/370 by changing from A to B, but we'd never deliberately decided on which is the intended behavior.

```diff
  namespace n {
  extern "C" {
  void n$cxxbridge05$f() noexcept {
-   void (*f$)() = f;       // 0.5.2 (A)
+   void (*f$)() = ::n::f;  // 0.5.3 (B)
    f$();
  }
  } // extern "C"
  } // namespace n
```

@adetaylor

**Comment by dtolnay** [comment]
It's possible what we want is actually more like:

```cpp
/* global namespace */
extern "C" {
void n$cxxbridge05$f() noexcept {
  using namespace ::n;
  void (*f$)() = f;
  f$();
}
} // extern "C"
```

**Comment by adetaylor** [comment]
Sorry for the inadvertent behavior change.

I don't have a firm need for either behavior - I anticipate specifying namespaces on everything in a fine-grained fashion.

I think my instinct is probably towards the more specific option (option B) just in case there are symbol conflicts (e.g. both `::n` and the global namespace contain `f`). But it's hard to think of a realistic scenario for such a conflict, and I assume for your internal use-cases behavior A is much easier.

**Comment by dtolnay** [comment]
I think what's in master right now is the strictest possible interpretation, so I am going to close this and we can re-evaluate if use cases for a different interpretation are brought forward down the line -- that can be a backward compatible change.
