### ISSUE TITLE
-std=c++11 is not required on MSVC

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cxx#44]
Building on x86_64-pc-windows-msvc currently emits this warning:

```console
warning: cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
```

According to https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2019, C++11 is the default with flags `/std:c++14` and `/std:c++17` for the newer standards.

We should find a way to pass `-std=c++11` only when it's required, such as on x86_64-apple-darwin where C++98 is the default. https://opensource.apple.com/source/clang/clang-800.0.42.1/src/tools/clang/www/cxx_status.html

```console
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/Users/travis/build/dtolnay/cxx/target/debug/build/cxx-f198c1b742072022/out/src/cxxbridge.o" "-c" "src/cxxbridge.cc"

In file included from src/cxxbridge.cc:1:
src/../include/cxxbridge.h:9:18: warning: 'final' keyword is a C++11 extension [-Wc++11-extensions]
class RustString final {
                 ^
```

**Comment by philipcraig** [comment]
I'm looking into this as part of #87
