### ISSUE TITLE
Permit Box<u8>?

### ISSUE THREAD

**Issue by XiangpengHao** [dtolnay/cxx#463]
Just noticed that `Box<u8>` (and all other primitive types) in the struct will be rejected

```
  c: Box<u8>,
   │^^^^^^^ unsupported target type of Box
```

https://github.com/dtolnay/cxx/blob/0e294981b8e6c0ad73dab5614f5bec6b0a95e8b9/syntax/check.rs#L82
and 
https://github.com/dtolnay/cxx/blob/0e294981b8e6c0ad73dab5614f5bec6b0a95e8b9/syntax/check.rs#L118

 look like a bug to me, or any concerns that I'm not aware of?

**Comment by dtolnay** [comment]
Do you have a use case for this?

**Comment by XiangpengHao** [comment]
Frankly speaking, what I need is raw pointer support, and the rationale behind `Box<u8>` is to express something like `char*` in c++.
(Just realized that Box might not be a good candidate for this though)

For some reason, I need to implement a struct similar to `Vec`, where a raw pointer will be pointed to a heap address so that it can store varaible length data.

**Comment by dtolnay** [comment]
Raw pointer support is tracked in #164. I would prefer to implement that directly and not Box\<u8\> as an approximation, so I'll go ahead and close this one.
