### ISSUE TITLE
Pointer type support

### ISSUE THREAD

**Issue by 2xsaiko** [dtolnay/cxx#479]
Unfortunately sometimes you do need to use raw pointer types (especially when dealing with Qt on the C++ side). cxx should support `T*` -> `*mut T`, `const T*` -> `*const T` (with special case `void*` -> `*mut ()` / `const void*` -> `*const ()`). Currently I'm circumventing this restriction by using usize as a pointer type but that's kind of a major hack :P

**Comment by adetaylor** [comment]
You can also use `UniquePtr` as an alternative hack. https://docs.rs/cxx/0.5.10/cxx/struct.UniquePtr.html#method.from_raw, https://docs.rs/cxx/0.5.10/cxx/struct.UniquePtr.html#method.into_raw and C++ side equivalents.

**Comment by dtolnay** [comment]
Pointer support is tracked in #164 so I'll go ahead and close this as a duplicate. I am definitely interested in this feature -- I think this just needs a PR...

**Comment by 2xsaiko** [comment]
Ah, my bad. I did look for open issues regarding this but must have missed that one.
