### ISSUE TITLE
Can't use Box<T> of the same Rust type in two different bridges

### ISSUE THREAD

**Issue by alexeyr** [dtolnay/cxx#480]
I have two `extern "Rust"` blocks here https://github.com/alexeyr/tokenizers/blob/f88d84b06f2503a312a051d710bd2596eba24ed4/bindings/cpp/src/normalizers.rs and here https://github.com/alexeyr/tokenizers/blob/f88d84b06f2503a312a051d710bd2596eba24ed4/bindings/cpp/src/pre_tokenizers.rs

```
    extern "Rust" {
        type NormalizedString;
        type NormalizerWrapper;
        type BertNormalizer;

        fn normalized_string(str: &CxxString) -> Result<Box<NormalizedString>>;

        fn bert_normalizer(
            clean_text: bool,
            handle_chinese_chars: bool,
            strip_accents: BertStripAccents,
            lowercase: bool,
        ) -> Box<BertNormalizer>;

        fn normalize_any(
            normalizer: &NormalizerWrapper,
            normalized: &mut NormalizedString,
        ) -> Result<()>;

        fn normalize_bert(
            normalizer: &BertNormalizer,
            normalized: &mut NormalizedString,
        ) -> Result<()>;
    }
```

```
    extern "Rust" {
        type NormalizedString;
        type PreTokenizedString;
        type PreTokenizerWrapper;
        type BertPreTokenizer;

        fn pre_tokenized_string(normalized: Box<NormalizedString>) -> Box<PreTokenizedString>;

        fn bert_pre_tokenizer() -> Box<BertPreTokenizer>;

        fn pre_tokenize_any(
            pre_tokenizer: &PreTokenizerWrapper,
            pre_tokenized: &mut PreTokenizedString,
        ) -> Result<()>;

        fn pre_tokenize_bert(
            pre_tokenizer: &BertPreTokenizer,
            pre_tokenized: &mut PreTokenizedString,
        ) -> Result<()>;
    }
```
Because both use `Box<NormalizedString>`, I get 
```
error: symbol `cxxbridge05$box$huggingface$tokenizers$ffi$NormalizedString$drop` is already defined
  --> src\pre_tokenizers.rs:17:49
   |
17 |         fn pre_tokenized_string(normalized: Box<NormalizedString>) -> Box<PreTokenizedString>;
   |                                                 ^^^^^^^^^^^^^^^^
```
This can be avoided by using references, of course, but then I need to clone the `NormalizedString` (which is probably safer anyway, and what I am planning to do). Or again, by defining everything in a single module, which I'd prefer to avoid. 

More generally, do I understand correctly that if I want to create an object on the Rust side and own it on the C++ side, I should use functions returning `Box`?

**Comment by dtolnay** [comment]
This isn't exactly the same issue but it is very closely related to #496, so I am going to close this issue in favor of tracking it together over there. https://github.com/dtolnay/cxx/issues/496#issuecomment-736253352 outlines how I intend to resolve both limitations.

**Comment by dtolnay** [comment]
> More generally, do I understand correctly that if I want to create an object on the Rust side and own it on the C++ side, I should use functions returning `Box`?

Correct, that's generally the best way.
