### ISSUE TITLE
unsafe extern "C++" blocks not recognized by compiler

### ISSUE THREAD

**Issue by nfk93** [dtolnay/cxx#485]
Using rustc 1.47.0 on wsl2. Any `unsafe extern "C++"` blocks are not recognized by the compiler. It seems the parser thinks you are about to declare an unsafe function. This happens also when compiling the demo code in cxx/demo. It happens for me in this somewhat minimal snippet:

```
#[cxx::bridge]
mod ffi {
    unsafe extern "C++" {
        include!("rust-ntl/include/zz.h");

        type ZZ;

        fn zz_from_u64(a: u64) -> UniquePtr<ZZ>;
    }
}
```

Which gives the following when running `cargo build`:

```
error: expected `fn`, found `{`
 --> src/main.rs:3:25
  |
3 |     unsafe extern "C++" {
  |                         ^ expected `fn`

error: aborting due to previous error

error: could not compile `rust-ntl`.
```

**Comment by dtolnay** [comment]
Rustc 1.48+ is required. See https://blog.rust-lang.org/inside-rust/2020/11/16/1.48.0-prerelease.html for installation.

**Comment by nfk93** [comment]
Works with rustc 1.48, thanks.
