### ISSUE TITLE
Cargo package compiles on its own, but compilation fails when included as a dependency

### ISSUE THREAD

**Issue by adamski234** [dtolnay/cxx#486]
I have a Cargo workspace package that uses cxx to link to [libqalculate](https://github.com/Qalculate/libqalculate) It works fine if I run `Cargo build -p package`. But if I try to use `package` as a dependency in the root package, it fails during linking. Why is that? Is that my fault or is that a fault of cxx? 

How to reproduce:  
Clone the https://github.com/adamski234/ars-parser repository and uncomment [these two lines](https://github.com/adamski234/ars-parser/blob/master/src/key_loader.rs#L43). Make sure you have libqalculate enabled. Then run `cargo build`. That fails. Running `cargo make` if you have it installed works fine, the package compiles with no issues.

My software:  
`rustc` 1.50  
`cxx` 1.0
`llvm` 11.0.0  

Relevant code:  
[The bridge](https://github.com/adamski234/ars-parser/blob/master/std_math/src/lib.rs#L51)

**Comment by dtolnay** [comment]
https://github.com/adamski234/ars-parser/blob/93afafca4db517eb834ba396c0e077e55f7e8410/std_math/build.rs#L2

`object("...")` is for `.o` files. I don't know what effect that has if you're passing `.so` and the linker is supposed to be producing `.so`. Apparently just ignored? To my knowledge you don't get to embed one of those things inside another.

I think it'll work if you remove `object` and use https://doc.rust-lang.org/1.48.0/cargo/reference/build-scripts.html#cargorustc-link-libkindname.

```rust
println!("cargo:rustc-link-lib=qalculate");
```

**Comment by adamski234** [comment]
This is interesting. I wonder why it worked when compiled on its own. Thanks, it works now.
