### ISSUE TITLE
Missing << operator for rust::String

### ISSUE THREAD

**Issue by mindv0rtex** [dtolnay/cxx#497]
This page https://cxx.rs/binding/string.html lists
```
std::ostream &operator<<(std::ostream &, const String &);
```
as a part of the `rust::String` public API, but it appears to be missing. The generated header file contains the following declaration:
```
class String final {
public:
  String() noexcept;
  String(const String &) noexcept;
  String(String &&) noexcept;
  ~String() noexcept;

  String(const std::string &);
  String(const char *);
  String(const char *, size_t);

  String &operator=(const String &) noexcept;
  String &operator=(String &&) noexcept;

  explicit operator std::string() const;

  const char *data() const noexcept;
  size_t size() const noexcept;
  size_t length() const noexcept;

  String(unsafe_bitcopy_t, const String &) noexcept;

private:
  std::array<uintptr_t, 3> repr;
};
```

**Comment by dtolnay** [comment]
The public API is what is declared by `#include "rust/cxx.h"`, which includes operator\<\<.

https://github.com/dtolnay/cxx/blob/9754dafe8a1e6f40785ae69dd32e20ed7384fa20/include/cxx.h#L277

It should be available if you add `#include "rust/cxx.h"`.

**Comment by mindv0rtex** [comment]
I see. I'm curious, what's the rationale behind duplicating significant potions of declarations between the `lib.rs.h`, `lib.rs.cc` and `cxx.h` files, but excluding some of them? Is this something to be cleaned up later? I'm better with C++ than Rust, but perhaps I could try to draft a PR for this if you give me some pointers of what needs to be tweaked?
