### ISSUE TITLE
Documentation for calling a Rust lib from a C++ bin?

### ISSUE THREAD

**Issue by jagill** [dtolnay/cxx#498]
My use case is writing a core lib in Rust with a C++ wrapper for others to interface.  I've struggled to find a way to produce a `libtest_cxx.a` and `libtest_cxx.h` that I can link to.  A small test repo showing my attempt is at https://github.com/jagill/test_cxx .  Things I've noticed that might be clues that I can't decipher:

1. `target/debug` has `libfoo.rlib`, which seems useful for Rust calling this.
2. `target/debug/build/test_cxx-$HASH/out/` has `libtest_cxx.a`, but no combined header that I can see.  I suppose I can copy over the individual headers?

If I was better at C/C++ perhaps I'd already have solved this.  I'd be happy to make a PR with the documentation, if you want to help me getting it working :).

**Comment by dtolnay** [comment]
If you want a static library as output (libtest_cxx.a), you need to put `[lib] crate-type = ["staticlib"]` in Cargo.toml. See https://doc.rust-lang.org/1.48.0/cargo/reference/cargo-targets.html#library and https://doc.rust-lang.org/1.48.0/reference/linkage.html.

The translated header is in target/cxxbridge/test_cxx/src/lib.rs.h.

**Comment by jagill** [comment]
This works great, thanks!
