### ISSUE TITLE
Define begin() and end() for rust::Str, String, Slice

### ISSUE THREAD

**Issue by alexeyr** [dtolnay/cxx#505]
`rust::Vec` already has `begin()` and `end()` which allows using it with a range-based for loop in C++. Adding similar members to `Str`, `String` and `Slice` would improve their ergonomics a bit.

**Comment by dtolnay** [comment]
Added in 1.0.5.

https://cxx.rs/binding/str.html
https://cxx.rs/binding/string.html
https://cxx.rs/binding/slice.html
