### ISSUE TITLE
Support opaque Rust types in a rust::Slice

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cxx#532]
Currently only primitives and shared types are supported in a slice in the FFI.

The following is currently rejected, but it should be possible to support:

```rust
#[cxx::bridge]
mod ffi {
    extern "Rust" {
        type MyType;
    }

    unsafe extern "C++" {
        fn f(slice: &[MyType]);
    }
}
```

The slice iterators and indexing operations will need to obtain a `stride` at runtime from Rust, exactly like we already do for rust::Vec containing opaque Rust types.

**Comment by alexeyr** [comment]
Can `&[String]` be supported as well?

**Comment by dtolnay** [comment]
`&[String]` should already be working. If not, please file a separate issue with a repro.

**Comment by alexeyr** [comment]
Sorry, I confused it with `&[&str]`, which doesn't seem to be.
