### ISSUE TITLE
Calling non-const methods is a bit more awkward now - is it intentional?

### ISSUE THREAD

**Issue by adetaylor** [dtolnay/cxx#546]
The pinning required for non-const C++ methods makes it more awkward to call them with a `UniquePtr`.

See https://github.com/dtolnay/cxx/compare/master...adetaylor:repro-method-problem for a full test case, but in brief:

```rust
 fn update(&mut self, blobid: u64) -> BlobMetadata;
```

gives

```
  error[cxxbridge]: mutable reference to C++ type requires a pin -- use `self: Pin<&mut BlobstoreClient>`
```

So:

```rust
fn update(self: Pin<&mut BlobstoreClient>, blobid: u64) -> BlobMetadata;
```

works, but calling it as a method:

```rust
let metadata2 = client.update(blobid);
```

does not. (`client` is a mutable `UniquePtr<BlobstoreClient>`).

```
error[E0599]: no method named `update` found for struct `UniquePtr<BlobstoreClient>` in the current scope
  --> demo/src/main.rs:60:28
   |
60 |     let metadata2 = client.update(blobid);
   |                            ^^^^^^ method not found in `UniquePtr<BlobstoreClient>`
```

It _does_ work if we call:

```rust
let metadata2 = client.as_mut().unwrap().update(blobid);
```

but I'm hoping that's not necessary and I'm doing something daft?

**Comment by dtolnay** [comment]
Exposing a &amp;mut to an opaque C++ type to Rust is problematic. For example something like `std::mem::swap::<BlobstoreClient>(client1, client2)` would have no idea what number of bytes to move around, and moving them around would inappropriately bypass a C++ move constructor or std::swap overload anyway.

For now you should use `client.pin_mut().update(blobid)` which will produce more useful panics than `as_mut().unwrap()`.

I am writing an RFC to enable calling `self: Pin<&mut Self>` methods on receivers with a suitable trait impl, which is also a frequent problem affecting pinned Box:

```rust
use std::pin::Pin;

struct Struct;

impl Struct {
    fn method(self: Pin<&mut Self>) {}
}

fn main() {
    let mut ptr: Pin<Box<Struct>> = Box::pin(Struct);
    ptr.method();
}
```

```console
error[E0599]: no method named `method` found for struct `Pin<Box<Struct>>` in the current scope
  --> src/main.rs:11:9
   |
11 |     ptr.method();
   |         ^^^^^^ method not found in `Pin<Box<Struct>>`
```

**Comment by adetaylor** [comment]
Thanks. I agree with your concerns and I'm delighted you're doing the RFC. I've never been involved in a Rust RFC before but if there's some kind of voting or starring or any other procedure where I can lend my support, I'd be delighted to do so.

Meanwhile, though, does this constraint need to apply to `cxx::kind::Trivial` `ExternTypes`? Currently it does. (I pushed another commit to https://github.com/dtolnay/cxx/compare/master...adetaylor:repro-method-problem demonstrating the situation).

Most types in my world are `cxx::kind::Opaque` so the need for `pin_mut()` on `Trivial` types is not a big deal to me, but I want to make sure I fit in correctly before upgrading to `cxx` 1.0.

**Comment by dtolnay** [comment]
It should be fine to allow it without pin for Trivial type aliases.

**Comment by adetaylor** [comment]
Thanks. Expect a PR, but possibly not for a week or so.

**Comment by adetaylor** [comment]
Here are the results of my investigation and my plan.

Currently `cxx` `check.rs` uses `is_opaque_cxx(cx, &ident.rust)` to determine whether to show the "mutable reference to C++ type requires a pin" message.

However, `is_opaque_cxx` refers to the `required_trivial` list. At `check` time, we don't know that the types in that list _are_ trivial, we just know that we _need_ them to be trivial - and will _later_ generate an error if their `ExternType` implementation says otherwise. We have no way of knowing at `check` time what it will say.

This can lead to confusing behavior. https://github.com/dtolnay/cxx/compare/master...adetaylor:repro-method-problem successfully demonstrates the problem, but when I tried to add identical code to the test suite, there was no error - because as it stands now, that message will only appear when the type needs to be `Trivial` for _some other reason_, and in the test suite it doesn't.

So I think the correct solution is as follows, and this is what I will be working towards.

* New `TrivialReason::MutableReferencePassedWithoutPinning`
* `types::collect` identifies this situation and adds a new entry to `required_trivial`
* Handle the new `TrivialReason` in the error message generated within `check_api_type`
* Pinning checks checks within `check.rs` remain unchanged
* Net behavior for an extern C++ type used as an un-pinned mutable reference parameter. We no longer ever see the "mutable reference to C++ type requires a pin" message, for extern C types. Instead:
  1. if the type is `ExternType::Kind` `Trivial`: it works
  2. if the type is `ExternType::Kind` `Opaque`: we get a build-time (post-`check`) error in all the fancy generic matching logic when we determine the type is not `Trivial`. It doesn't mention pinning (as far as I know)
  3. if the type has no `ExternType` implementation at all we will get "needs a cxx::ExternType impl in order to be used as a non-pinned mutable reference argument to <function>"

I think this is consistent with what we've done in other cases when such a type needs to be `Trivial` but case 2 is non-optimal. I'm wondering if there's a way to sneak the `TrivialReason` into the error message presented when a type turns out to be `Opaque` after all. I'll look into that when I have done all the rest.
