### ISSUE TITLE
How to store a `rust::Box<T>` as a member of a C++ class

### ISSUE THREAD

**Issue by cquintana-verbio** [dtolnay/cxx#552]
Hi!
First of all, thank you very much for your hard work on this library. I've been following it for some time, and now I think I'm ready to use it.

However, I've encountered a situation that I'm not sure how to handle.

I want to create a library in Rust, and call it from my C++ code.

The structure will be something like the following:

```c++
// MyThing.h
class MyThing {
public:
  MyThing(const std::string& name);
  ~MyThing();
  void greet() const;
private:
  rust::Box<RustThing> thingImpl;
}

// MyThing.cpp
MyThing::MyThing(const std::string&name) {
  thingImpl = create_thing_impl(name); // Call to Rust function
}

void MyThing::greet() const {
  thingImpl.greet();
}
```

The C compiler is complaining about `rust::Box` having a private constructor, as it's trying to call it for an automatic initialization. Is there a recommended way for doing that?

**Comment by dtolnay** [comment]
Indeed `Box` is not default constructible. There is no such thing as a null Box or empty Box.

You need to not default construct the box prior to entering the constructor body.

```rust
MyThing::MyThing(const std::string& name) : thingImpl(create_thing_impl(name)) {}
```

**Comment by cquintana-verbio** [comment]
That worked, thanks!
