### ISSUE TITLE
How to pass a C++ cxx:SharedPtr<T> pointer to primitive type (u8, u16) to rust?

### ISSUE THREAD

**Issue by noncomfortzone** [dtolnay/cxx#562]
Hi all,

I want to pass a C++ shared pointer to rust, the pointed type is u32. But if I coded as:
```rust
pub fn create_image(data: SharedPtr<u32>) -> SharedPtr<Image> {
    unimplemented!()
}
```
the compiler will report "the trait `SharedPtrTarget` is not implemented for `u32`"。

How can fix that? Thanks.

**Comment by dtolnay** [comment]
This was just not implemented yet. I published cxx 1.0.15 with the impls.
