### ISSUE TITLE
Failed to compile C++ code if return a boxed opaque rust type Box<OpaqueRust>

### ISSUE THREAD

**Issue by noncomfortzone** [dtolnay/cxx#567]
C++ compiler will complaint that "error C2027 undefined type `OpaqueRust`". 

```rust
extern "Rust" {
  type OpaqueRust;
  fn call() -> Box<OpaqueRust>;
}
```

It happed line 85 of generated C++ code:
```C++
template <typename T>
Box<T> &Box<T>::operator=(const Box &other) {
  if (this != &other) {
    if (this->ptr) {
      **this = *other;
    } else {
      this->uninit();
      ::new (this->ptr) T(*other);
    }
  }
  return *this;
}

```

It looks `T(*other)` will failed if T is opaque.

**Comment by dtolnay** [comment]
I was not able to reproduce this. It works in our test suite: https://github.com/dtolnay/cxx/blob/1.0.16/tests/ffi/lib.rs#L205. Could you provide all of the code involved to reproduce the error?

**Comment by dtolnay** [comment]
I haven't heard back so I am going to take a guess that there was a missing `std::move` somewhere in your C++ code. C++ can't copy construct or copy assign a Box\<T\> unless it has some idea of how to obtain a second T from an existing T, which is not the case for opaque types.
