### ISSUE TITLE
Provide a `swap` implementation for types in cxxbridge.h

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cxx#58]
As recommended in #8. String, Str, and Box should have an efficient `swap`.

**Comment by capickett** [comment]
@dtolnay bit of a github newbie here, but I've taken a stab at addressing this issue in #642. Is there any way to "claim" issues, or should I expect that you'll handle closing issues accordingly?

**Comment by dtolnay** [comment]
If you put "Closes #58" or "Fixes #58" or "Resolves #58" in the PR summary then it will close automatically when merged.
