### ISSUE TITLE
Generated code doesn't compile with `-Werror=missing-declarations`

### ISSUE THREAD

**Issue by cgwalters** [dtolnay/cxx#590]
I find [-Werror=missing-declarations](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmissing-declarations) very useful, but the cxx-generated code doesn't build with this.  Reproducer:

```
diff --git a/demo/build.rs b/demo/build.rs
index c1b55cc..74492fd 100644
--- a/demo/build.rs
+++ b/demo/build.rs
@@ -2,6 +2,7 @@ fn main() {
     cxx_build::bridge("src/main.rs")
         .file("src/blobstore.cc")
         .flag_if_supported("-std=c++14")
+        .flag("-Werror=missing-declarations")
         .compile("cxxbridge-demo");
 
     println!("cargo:rerun-if-changed=src/main.rs");
```

```
$ cargo build
...
 cargo:warning=/var/srv/walters/src/github/dtolnay/cxx/target/release/build/demo-c98f284132a5867d/out/cxxbridge/sources/demo/src/main.rs.cc:765:6: error: no previous declaration for 'void cxxbridge1$unique_ptr$org$blobstore$BlobstoreClient$drop(std::unique_ptr<org::blobstore::BlobstoreClient>*)' [-Werror=missing-declarations]
  cargo:warning=  765 | void cxxbridge1$unique_ptr$org$blobstore$BlobstoreClient$drop(::std::unique_ptr<::org::blobstore::BlobstoreClient> *ptr) noexcept {
  cargo:warning=      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=cc1plus: some warnings being treated as errors
  exit code: 1
```

I successfully worked around this by making a little libtool library that builds these without `-Wno=missing-declarations` of course, so I'll do that for now.  But I'd like to apply consistent warning flags across my codebase.

I took a look at the code here and started adding various
```
From ab74d704c3f0623d953304a8a34402ef7f27be48 Mon Sep 17 00:00:00 2001
From: Colin Walters <walters@verbum.org>
Date: Tue, 22 Dec 2020 01:29:42 +0000
Subject: [PATCH] wip

---
 gen/src/write.rs | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/gen/src/write.rs b/gen/src/write.rs
index 315fb35..2b0fa1a 100644
--- a/gen/src/write.rs
+++ b/gen/src/write.rs
@@ -1584,6 +1584,8 @@ fn write_unique_ptr_common(out: &mut OutFile, ty: UniquePtr) {
     );
     writeln!(
         out,
+        "void cxxbridge1$unique_ptr${}$null(::std::unique_ptr<{}> *ptr) noexcept;",
+    writeln!(
         "void cxxbridge1$unique_ptr${}$null(::std::unique_ptr<{}> *ptr) noexcept {{",
         instance, inner,
     );
-- 
2.29.2

```

but it probably wants more abstraction?  If this seems like the right approach I can try to do a PR.

**Comment by cgwalters** [comment]
The reason I like this warning is it highlights when two pieces of code should include a shared header file.  However in this case as far as I can tell, these "C bridge functions" are implicitly shared between template code from `cxx.cc` from this crate and generated code in the user crate, so a shared header wouldn't be possible?

**Comment by dtolnay** [comment]
That GCC lint is blatantly designed for pure-C/C++ code, which this crate is not. In the way that this crate uses extern functions across languages (defined in one, declared in the other), that lint would not provide value, and preceding every definition with an identical declaration for no other purpose than to please the lint would purely be noise. Building cxx with that lint suppressed is going to be the correct fix for you.
