### ISSUE TITLE
Reusing simple structs in the bridge interface

### ISSUE THREAD

**Issue by Timmmm** [dtolnay/cxx#670]
We have a Rust API that we're trying to expose to C++. It has a ton of simple structs like this:

```rust
#[derive(Debug)]
pub struct LibVersion {
  pub string: String,
  pub package_hash: String,
  pub major: u32,
  pub minor: u32,
  pub point: u32,
}

#[derive(Debug, Clone)]
pub struct CompilationTraceEvent {
  pub cat: String,
  pub dur: u64,
  pub name: String,
  pub ph: String,
  pub pid: u32,
  pub tid: u32,
  pub ts: u64,
}

pub struct ItemType {
  pub name: String,
  pub size: u64,
  pub source: ItemSource,
}

#[derive(Debug, Copy, Clone)]
pub enum ItemSource {
  A,
  B,
}
```

You get the idea. In order to expose these to C++ the obvious but annoying thing to do is to copy/paste them all into the `mod ffi {` and then tediously add `From` implementations. Obviously not ideal!

The second best solution that I can think of at the moment is to move everything into the `ffi` mod, and then we can add `pub use ffi::LibVersion` etc. which is much less tedious. I think this will work, but it seems like only `Copy` and `Clone` auto-derive traits are supported by the macro.

I assume the proc macro system only gives you the contents of the macro, so you could never do something like `mod ffi { type LibVersion = super::LibVersion; }` because then your proc macro has no idea what the fields of `super::LibVersion` are - is that right?

I'm not sure what the solution is here but it's definitely an annoying problem....

**Comment by arvid220u** [comment]
Has anyone figured out what to do in this situation? CXX seems awesome but we have a lot of structs with custom `derive`s and have run into exactly the same problem here...

**Comment by casimcdaniels** [comment]
@Timmmm Did you ever figure out a workaround for this?

**Comment by Timmmm** [comment]
I don't think so, sorry. :-/

**Comment by dtolnay** [comment]
The discussion under #1077 lays out the supported options for reusing simple structs in the bridge interface.
