### ISSUE TITLE
How to force the use of the old ABI (CentOS 7 compatible)

### ISSUE THREAD

**Issue by cquintana-verbio** [dtolnay/cxx#673]
Hi! First of all, thank you for your work in the library.

I'm working in a Rust project that:

- Has C dependencies generated by CentOS 7.
- Generates a static library (.a) needs to be linkable in CentOS 7 (GCC 7).

If you compile the library in CentOS 7, it works flawlessly. However, I usually work in Debian, and in other projects I can just add the following line in my `CMakeLists.txt` files in order to force the compiler to use the old ABI (the one used in CentOS 7):

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0")
```

However, I'm not able to set that directive when using CXX to build my Rust library. I've tried using the following `build.rs` with no luck:

```rust
// build.rs
fn main() {
    cxx_build::bridge("src/lib.rs")
        .static_flag(true)
        .define("_GLIBCXX_USE_CXX11_ABI", "0")
        .compile("cxxbridge-demo");

    println!("cargo:rerun-if-changed=src/");
}
```

In order to check it the ABI being used:

```
$ cargo build --release
$ nm -C target/release/*.a | grep cxx11
0000000000000000 T rust::cxxbridge1::Str::Str(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0000000000000000 T rust::cxxbridge1::Str::Str(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0000000000000000 t rust::cxxbridge1::Str::Str(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold]
0000000000000000 T rust::cxxbridge1::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0000000000000000 T rust::cxxbridge1::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
0000000000000000 t rust::cxxbridge1::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold]
0000000000000000 T rust::cxxbridge1::Str::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const
0000000000000000 T rust::cxxbridge1::String::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)
                 U std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)
```

The `std::__cxx11::basic_string` indicates that the "new" ABI is being used. When the "old" ABI is being used, the output should be the following:

```
$ cargo build --release
$ nm -C target/release/*.a | grep cxx11
$ # No matches
```

I'm not sure if this is a behaviour of the CXX build process or the Rust compiler process. If you have any hint about how to generate the library from Debian but with the old ABI it would be great!

Thanks in advance.

**Comment by dtolnay** [comment]
Does it work with `CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 cargo build --release`?

**Comment by cquintana-verbio** [comment]
OMG, that was it. I tried using `RUSTFLAGS` and CXX definitions, but did not try CXXFLAGS.

Thanks a lot!

**Comment by dtolnay** [comment]
Sounds good. Those symbols in your nm output are not coming from the cc invocation in the build.rs that you were touching. It's from some other cc build in the dependency graph.

Here are more configurations that might be relevant to you: https://github.com/alexcrichton/cc-rs#external-configuration-via-environment-variables

**Comment by cquintana-verbio** [comment]
Thanks a lot for the help and the reference, I will surely take a look at it!
