### ISSUE TITLE
Use cxx without C++ source

### ISSUE THREAD

**Issue by Tarang** [dtolnay/cxx#674]
I just went through the tutorial on how to use cxx and its a fantastic project!

I have a static library and header files but no C++ source code. Is it still possible to use cxx with that?

**Comment by dtolnay** [comment]
Yes, that should be no problem. All we look at is the header. If building with Cargo, you can link the extra static library using https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname from build.rs:

```rust
// build.rs

fn main() {
    ...

    println!("cargo:rustc-link-search=path/to");
    println!("cargo:rustc-link-lib=mylibrary");
}
```

where `path/to` is either absolute, or relative to the workspace root, and the static library exists at `path/to/libmylibrary.a` (or whatever static library extension is appropriate to the platform).

**Comment by semirix** [comment]
So currently I'm linking against a static lib and I keep getting this error:
```
undefined reference to `Lib$API$cxxbridge1$init'
```
Where `Lib::API` is the namespace and `init` is the function. I think there is an issue with name mangling that is preventing me from linking this. Do you have any insights @dtolnay?

**Comment by semirix** [comment]
This is the code that I'm trying to get to work:
```rust
#[cxx::bridge]
mod ffi {
    #[derive(Debug)]
    enum ReturnCode {
        ...
    }

    #[namespace = "Lib::API"]
    unsafe extern "C++" {
        include!("../../..api/include/lib/api/api.h");

        fn init(user_application_name: &str) -> ReturnCode;
    }
}

fn main() {
    let result = ffi::init("foo");
    println!("Hello, world! {:?}", result);
}
```

**Comment by dtolnay** [comment]
Something is missing from your build.rs. Are you able to share the build.rs?

**Comment by semirix** [comment]
```rust
fn main() {
    println!("cargo:rustc-link-search=native=api/lib");
    println!("cargo:rustc-link-lib=static=lib"); // This is a proprietary lib I can't share
    println!("cargo:rustc-link-lib=bz2");
    println!("cargo:rustc-link-lib=ssl");
    println!("cargo:rustc-link-lib=crypto");
    println!("cargo:rustc-link-lib=z");
}
```

**Comment by dtolnay** [comment]
It seems like nothing in there has run CXX's code generator? If using Cargo, you need to follow https://cxx.rs/build/cargo.html (also shown in the tutorial). That's what defines the symbol you were missing.

**Comment by semirix** [comment]
Ah yes, that has worked! Thank you!
