### ISSUE TITLE
Build depending on external library "linbox" fails with "multiple definition" errors

### ISSUE THREAD

**Issue by RobinStoll** [dtolnay/cxx#695]
For a project of mine, I need to work with the [linbox](https://github.com/linbox-team/linbox) library. After not managing to get it to work with cxx, I did a minimal test using the cxx-demo: I added

    #include <linbox/matrix/dense-matrix.h>

to the imports of `blobstore.h`. Subsequently running `cargo build` fails in the linker stage with a large number of `multiple definition` errors, such as the following:

    [...]/ld: [...]/demo/target/debug/build/demo-d1dc2d9abadacf19/out/libcxxbridge-demo.a(blobstore.o): in function 'LinBox::nroot(double, long, double)':
    /usr/include/linbox/util/commentator.inl:57: multiple definition of 'LinBox::nroot(double, long, double)'; [...]/demo/target/debug/build/demo-d1dc2d9abadacf19/out/libcxxbridge-demo.a(main.rs.o):/usr/include/linbox/util/commentator.inl:57: first defined here

The problem seems to be that various definitions are included both in `blobstore.o` and `main.rs.o` (at least that's what I gleaned; I am however not very experienced with neither C++ nor Rust).
Maybe this has to do with linbox being organized mostly as header files including `.inl` files instead of things being separated into separate source files?

I'd be happy about any suggestions about how to fix or circumvent this issue.

**Comment by dtolnay** [comment]
This is a linbox bug &mdash; [commentator.h inappropriately includes commentator.inl](https://github.com/linbox-team/linbox/blob/8fbc944955e2ca2a5eedfe2e81b27e9f9c756afe/linbox/util/commentator.h#L809), which compiles duplicate non-inline functions into every translation unit that transitively includes commentator.h. This is an [ODR violation](https://en.cppreference.com/w/cpp/language/definition) (undefined behavior).

**Comment by RobinStoll** [comment]
Ok, thanks. That's what I feared. Do you know of any work-around that would allow me to circumvent this?

**Comment by dtolnay** [comment]
I think linbox just explicitly doesn't support your use case. https://github.com/linbox-team/linbox/issues/82 has relevant discussion. They insist on 1 global translation unit which implicitly assumes 1 language. I'll go ahead and close this since you would need to follow up with them.

**Comment by RobinStoll** [comment]
Ah, that's unfortunate. Thanks for the help!
