### ISSUE TITLE
Can't use an opaque C++ type from a different bridge/namespace

### ISSUE THREAD

**Issue by jlebon** [dtolnay/cxx#720]
In https://github.com/coreos/rpm-ostree/pull/2568, we're trying to make use of an opaque C++ type in one crate bridge which has its `ExternType` implemented in a separate crate (which has its own bridge). The situation is like this:

- The library `rpmostree_rust` from the crate `rpmostree-rust` wants to use type `DnfPackage` as a parameter of a function in the `rpmostreecxx` bridge.
- The type `DnfPackage` is defined in the library `libdnf-sys` as an opaque C++ type and is part of a `dnfcxx` bridge. The library implements `ExternType`: https://github.com/coreos/rpm-ostree/blob/04839e200f94413aa2c8da1af816ca70f77feb19/rust/libdnf-sys/lib.rs#L17-L21
- We want to tell CXX in the `rpmostree-rust` crate to use the `DnfPackage` type from the `libdnf-sys` crate, which on the C++ side is a type defined in the `dnfcxx` namespace and not `rpmostreecxx`.

Is there any way to do this presently?

One workaround is to rename the bridge in `libdnf-sys` to be the same (this is what https://github.com/coreos/rpm-ostree/pull/2568 does for now). Another workaround is to use the newtype pattern and re-implement `ExternType` in `rpmostree-rust`. Though I was hoping to avoid the boilerplate that implies converting between them.

**Comment by dtolnay** [comment]
It sounds like what you are looking for is:

```rust
#[cxx::bridge]
mod ffi {
    extern "C++" {
        ...

        #[namespace = "dnfcxx"]
        type DnfPackage = libdnf_sys::DnfPackage;
    }
}
```

<br>

This is documented in https://cxx.rs/attributes.html#namespace.

**Comment by jlebon** [comment]
Ahh great, thanks! Not sure how I missed that.
