### ISSUE TITLE
CXX FFI types that own resources without heap allocation

### ISSUE THREAD

**Issue by sbrocket** [dtolnay/cxx#721]
This is a carry-over from #708. From that issue (and in the context of a hypothetical type that owns some resource which must be freed or closed to avoid leaks; imagine a type wrapping a file descriptor or other OS resource, or perhaps std::unique_ptr):

> > It'd be nice to be able to create types on the FFI interface that 1) don't require heap allocation (Box/unique_ptr) and 2) can guarantee that owned resources are closed or cleaned up appropriately.
> 
> ExternType is the way to do this -- along the lines of https://cxx.rs/extern-c++.html#integrating-with-bindgen-generated-or-handwritten-unsafe-bindings. You can handwrite a destructor for the drop logic on the C++ side, using a drop flag or some other sentinel value for the moved-from state.

I don't see how ExternType currently allows for satisfying both of the stated requirements. A trivial extern type can't have a destructor (or if it did have a destructor it wouldn't be called once the type was passed-by-value to Rust code). It also wouldn't be appropriate because a resource-owning type like this needs to be a move-only type, and thus have a non-trivial move constructor. Am I missing your meaning from the quoted text?

Perhaps I should just live with the heap allocation, but it feels wasteful (especially since the first thing done with the value after passing it across the FFI is to convert it to the native wrapper type) and makes the interface somewhat awkward, which is why I was hoping to create a shared type that gets cleaned up appropriately. This also seems likely enough to be a pattern that others will want to use; specifically, passing types that own resources between Rust and C++, where you always want the value in an auto-closing type to avoid leaks.

What would you think of a new attribute that could be attached to a shared type to make it a C++ move-only type with a specified sentinel value? Such a type would have non-trivial move constructors generated by cxxbridge and deleted copy constructors, plus a generated destructor that calls std::drop_in_place if the value is not the sentinel (which is fine whether or not Drop is implemented). We'd also avoid generating the placeholder Drop impl that you added in #711 for these types.

```
#[cxx::bridge(namespace = foo)]
mod ffi {
    #[move_only(sentinel = "raw", value = "0")]
    struct Handle {
        raw: u32,
    }
}
```
(TBD on the specific attribute syntax)

Or do you have another suggestion, either that involves new features or not?

**Comment by dtolnay** [comment]
It should be possible to do with a `Trivial` kind on the ExternType impl. That just means Rust is allowed to bitwise relocate the type as part of a Rust move.  You will also need to follow https://github.com/dtolnay/cxx/blob/1.0.32/include/cxx.h#L415 to get the destructor check disabled.

**Comment by dtolnay** [comment]
To be more explicit: my expectation would be something along the lines of:

```rust
#[repr(C)]
struct Handle {
    raw: u32,
}

unsafe impl ExternType for Handle {
    type Id = type_id!("Handle");
    type Kind = cxx::kind::Trivial;
}

impl Drop for Handle {
    fn drop(&mut self) {...}
}
```

```cpp
struct Handle {
  uint32_t raw;
  ~Handle() {...}
}
```

**Comment by sbrocket** [comment]
Right, duh. That probably should have occurred to me. :) Thanks!
