### ISSUE TITLE
Add explicit cxx_build API to only generate files

### ISSUE THREAD

**Issue by Timmmm** [dtolnay/cxx#728]
If you use `cxx_build` to compile the `lib.rs.cc` code to a library (e.g. `libbridge-demo.a`) it puts it in a randomly named subdirectory that is hard to find.

Our current solution is to just ignore that file, and use CMake (ugh) to recompile the generated `lib.rs.cc` file since it is at a knowable path.

In order to avoid compiling it twice I've changed the build.rs script to this:

```
    let _ = cxx_build::bridge("src/cpp_api.rs");
```

But it seems a bit fragile - I would imagine at some point it could potentially be changed so the code gen is done lazily. It would be nice to have an API like `cxx_build::generate("src/cpp_api.rs")` that did the same thing but was guaranteed to work. It could potentially be a string->string conversion instead of file->file.

**Comment by adetaylor** [comment]
There's the `cxx_gen` library for this: use [this API here](https://github.com/dtolnay/cxx/blob/master/gen/lib/src/lib.rs#L49). Does that do what you need? Note that the library code generator interface is not yet stabilized.

**Comment by adetaylor** [comment]
It's very easy to get from a string to a `TokenStream`: https://stackoverflow.com/questions/54165117/convert-string-into-tokenstream... it would be just a couple more lines to make it into what you want. Similarly the output is essentially `Vec<u8>` so very nearly a string.

Feel free to raise a PR to enhance the API with a rationale for why you can't readily convert to/from these types.

**Comment by dtolnay** [comment]
> If you use `cxx_build` to compile the `lib.rs.cc` code to a library (e.g. `libbridge-demo.a`) it puts it in a randomly named subdirectory that is hard to find.

@Timmmm you can override where to put it.

```rust
let where_to_put_it = Path::new("path/to/anywhere");
let cargo_out_dir = std::env::var_os("OUT_DIR").unwrap();
std::env::set_var("OUT_DIR", where_to_put_it);
cxx_build::bridge("src/main.rs")
    ...
    .compile("bridge-demo");  // writes $where_to_put_it/libbridge-demo.a
std::env::set_var("OUT_DIR", cargo_out_dir);
```

Note that depending on how you'll be linking, you may additionally need to inform the linker about your choice of directory, since Cargo won't otherwise search it for compiled libraries.

```rust
let cargo_manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
let abs_link_dir = Path::new(&cargo_manifest_dir).join(where_to_put_it);
println!("cargo:rustc-link-search={}", abs_link_dir.to_string_lossy());
```

`cxx_gen` is probably less good for your use case because the error reporting is not as good as cxx_build.

**Comment by dtolnay** [comment]
It sounds like the issue is asking for a way to *write* the generated source code files but not *compile* them, whereas the described use case just requires being able to obtain the compiled library at a predictable path. Does the previous comment resolve this for you or do you need a separate generate-but-not-compile functionality still?

**Comment by Timmmm** [comment]
> It's very easy to get from a string to a TokenStream: https://stackoverflow.com/questions/54165117/convert-string-into-tokenstream.

I think you have a different definition of "very easy" to me! Compare the amount of thinking I'd have to do for that vs if it was `&str -> String`. I have to find out what a `TokenStream` is - is it even possible to convert a string to a `TokenStream`? I don't know. Then I find that answer but do I want `proc_macros` 1 or 2? Who knows. I guess I copy the version used in `cxx_build`. Then I have to find the `Cargo.toml` in this repo... and see it's actually not nearly as simple as just supplying a string.

The `GeneratedCode` struct looks nice and simple though so probably `&str -> GeneratedCode` would be best. I don't see what the issue is with providing a convenience method.

> you can override Cargo's choice of where to put it.

Ah that is very useful! Seems a little hacky but not too bad. Definitely worth adding to the docs! Tbh I'm still a bit confused why it is saved in a random directory by default. Are users not supposed to link with it directly? How do other people do this?

> It sounds like the issue is asking for a way to write the generated source code files but not compile them

Yeah that is correct. I think even with your `OUT_DIR` workaround we'd probably still prefer to use CMake, since this is (sadly) part of a bigger CMake build system.
