### ISSUE TITLE
Undefined symbols if cxxbridge is not in the root module

### ISSUE THREAD

**Issue by Timmmm** [dtolnay/cxx#729]
If I defined my

    #[cxx::bridge]

in the root module (`lib.rs`) then I've got everything to work. But if I move it to a submodule and `pub use that_submodule` then a get a ton of linker errors, including for stuff generated by the proc macro (e.g. `rust::cxxbridge1::Str::Str(basic_string)`).

Is it a requirement that all of the `#[cxx::bridge]` has to be in the root module? Ours is pretty long and I'd like to put it in a separate file.

**Comment by adetaylor** [comment]
The test suite contains a `#[cxx::bridge]` in a module. See [the outer module](https://github.com/dtolnay/cxx/blob/master/tests/ffi/lib.rs) and [the included module](https://github.com/dtolnay/cxx/blob/master/tests/ffi/module.rs).

Perhaps the C++ codegen just isn't spotting the `#[cxx::bridge]` in the module, so none of the C++-side parts of the cxx bridge are being generated? Note that the build script does need to know which files to search for `#[cxx::bridge]` mods, [like this](https://github.com/dtolnay/cxx/blob/master/demo/build.rs#L2).

If these hints don't help, please include lots more information about the code layout, build script, and errors you're seeing.

**Comment by Timmmm** [comment]
The C++ parts are generated fine - I verified the `.rs.cc` file is the same in both cases. It's the C++ functions that are generated in Rust that are the problem.

That example code still has `#[cxx::bridge]` in the root module. I wonder if I can just add an empty one to make it work.

Oh, also after giving up on this and going back to the original code I remembered why I wanted it in the first place. I want to do this:

```
#[cfg(cpp_api)]
mod cpp_api;
```

It's pretty tedious to add `#[cfg(cpp_api)]` to every item in the root module otherwise.

**Comment by Timmmm** [comment]
Ok, I just tried this again, but this time I did

```
#[cfg(feature = "cpp_api")]
```

And it worked. Not sure why. I wish `cfg()` was better documented!
