### ISSUE TITLE
Passing const reference type from C++ to Rust

### ISSUE THREAD

**Issue by alexkirsz** [dtolnay/cxx#731]
Hello,

Thanks for making cxx! It feels like magic. The development experience is surprisingly smooth for someone like me who hasn't written C++ in a while ♥️

**(1)**
If I have the following function with the following signature from the C++ side, where `T` is an opaque C++ type
```cxx
T get_value();
```
From what I understand, the best practice is to wrap `T` in a `unique_ptr`, so the function becomes
```cxx
std::unique_ptr<T> get_value_wrap() {
  // Not 100% sure about this, my C++ is very rusty
  return std::make_unique<T>(std::move(get_value()));
}
```

**(2)**
Now let's say my function returns a reference instead
```cxx
T const& get_ref();
```
What's the blessed way to convert this into something that I can pass on to the Rust side?

**Context:**
I'm wrapping a C++ library which I don't own that returns types such as:
* `std::vector<std::array<uint32_t, 3>>`, for which I use option **(1)** with a custom `CxxVector_u32_3` for now
* `std::vector<std::vector<std::string>> const&` which I'm not sure how to best expose to the Rust side, see **(2)**
* a lot of the aforementioned `T const&`, also **(2)**

**Comment by dtolnay** [comment]
You can return a C++ reference into Rust as a Rust reference to opaque type. https://cxx.rs/binding/cxxstring.html#example has an example containing this -- see `getObject` which returns `std::map<string, json> const&`.

**Comment by alexkirsz** [comment]
Awesome! For some reason I was under the impression that I could only declare my own types in the `extern "C++"`, but it makes perfect sense that I should be able to declare aliases to any type.

Thanks for the quick reply!
