### ISSUE TITLE
Support returning CxxString as rust::String

### ISSUE THREAD

**Issue by mikhailzagurskiy** [dtolnay/cxx#740]
We need to support functions, that return `std::string` by value:

```c++
class Foo {
virtual ~Foo() = 0;
virtual std::string toString() const = 0;
};

class Bar final : public Foo{
~Bar() {}
std::string toString() const {
// returns some new std::string
}
};

std::shared_ptr<Foo> makeFoo() {
  return std::make_shared<Bar>();
}
```

It would be great, if we could do auto binding like this:

```rust
#[cxx::bridge]
mod ffi {
  unsafe extern "C++" {
    type Foo;
    
    fn makeFoo() -> SharedPtr<Foo>;

    fn toString(self: &Foo) -> String;  // Auto binding std::string by value to rust::String
  }
}

fn main() {
  //...
  let foo = makeFoo();
  println!("Foo is {}", foo.toString());
  //...
}
```

It's logical - when we return the `std::string` by value from some function, we want the `std::string` to be owned by caller code

**Comment by b05902132** [comment]
It seems that you cannot own a `CxxString` in Rust. https://github.com/dtolnay/cxx/blob/3dafaede930026394649639ac0798aa39d6b439f/src/cxx_string.rs#L26-L33
I did a quick Googling, and found that C++ standard seems to allow [this implementation](https://stackoverflow.com/a/50377102). If so, then there's no way to pass a `std::string` to Rust safely, due to different move semantics in Rust (moving in Rust is just `memcpy`).

**Comment by mikhailzagurskiy** [comment]
It seems, that you misunderstood the concept in the message above. 
We do not need to own a CxxString in rust. If C++ function returns std::string by value, it means the function doesn't care about the string.
We can just get content of the std::string and put it to the rust::String, then pass latter by the value.  We don't have to own the first stdd::string at all

**Comment by b05902132** [comment]
Sorry. I deleted the comment after I realized that.

**Comment by dtolnay** [comment]
I would prefer not to do this. `std::string` and Rust `String` are totally different types with different invariants, and it would be inappropriate to silently + lossily + expensively transform one into the other at the level that CXX is targeting.

**Comment by dtolnay** [comment]
To be more explicit on "lossily" -- the Rust String type has a utf8 invariant whereas it's possible for std::string to be any arbitrary bytes. Transforming arbitrary bytes into utf8 is either lossy or fallible, neither of which is a good fit for CXX to be doing automatically in a signature like that.

**Comment by mikhailzagurskiy** [comment]
Ok, maybe we should have some `Trait` or directive to mark the method return type to be auto-converted.

Because if you have the library with the interface:

```
namespace NS {
struct IReadable {
static std::shared_ptr<IReadable> create();
virtual std::string toString() const = 0;
}
}
```

You can't just declare `toString` method in an `rs`  file like this:

```
//...
type IRedable;
fn toString(self: &IRedable) -> CxxString;
//...
```

Because you can't give the result of the method by value. You have to write wrapper to convert the `std::string` to `rust::String` for each method, like this in the C++ code. But now, you can't just call it like a method of the interface, you must do a lot of work. Look at this:

File `wrapper.hpp`
```
namespace NS {
std::shared_ptr<IReadable> IReadable_create();  // This one, because you can't declare static method of the class
rust::String _IReadable_toString(const std::shared_ptr<IReadable>& myself);  // This one, because you can't return `std::string` by value
}
```
I omit `wrapper.cpp`  to simplify, but you understand it's quite simple because it's just a boilerplate.

Now, you have to do following code inside your `main.rs`
```
//... In cxxbridge
type IRedable;
fn IReadable_create() -> SharedPtr<IReadable>;
fn _IReadable_toString(myself: &SharedPtr<IReadable>) -> String;  // Coz you can't just pass an IReadable by const reference
//...

//... below cxxbridge
impl IRedable {
 pub fn create() -> SharedPtr<IReadable> {
  return IReadable_create();
 }
 pub fn toString(myself: &SharedPtr<IReadable>) -> String {
  return _IReadable_toString(myself);
 }
}

fn main() {
  let a = IReadable::create();  //  It's a necessary evil
  let s = IReadable::toString(&a);  // It's ugly, isn't it?
}
```

And it's not so hard if I have only one class with the `toString` method. But **NO!**
I have about 30 classes with those methods, and I have to write about 30 wrappers, as I described above.


But it's unnecessary, isn't it? The `CXX` could just auto generate binding from the `std::string` to `rust::String` (we have methods `data()` and `size()` inside the `std::string`, it's enough). And if someone returns just `std::string` by value from the function, he **doesn't want to know who owns that string and how**. 

If I marked the method above like this:
```
//...
type IRedable;
#[derive(AutoConvertReturnedString)]                                // Something like that
fn toString(self: &IRedable) -> String;
//...
```

I can decide, if it's a good idea to auto convert this particular returned value from the `std::string` to the `rust::String`

**Comment by adetaylor** [comment]
[autocxx](https://github.com/google/autocxx) is designed to make it easier to use `cxx` to interface with _existing_ code. It's still pretty immature but you might want to have a look.

For the specific case of functions which return `std::string`, it creates a C++ wrapper function which converts the `std::string` to `std::unique_ptr<std::string>`. `cxx` can cope happily with that type in the form of `UniquePtr<CxxString>`. That way, you don't have to deal with any of the UTF8 issues which dtolnay@ mentions: instead the recipient code in Rust can decide whether to convert to a byte buffer, lossily convert to UTF8 or checked convert to UTF8.

**Comment by mikhailzagurskiy** [comment]
Yeah, but the official documents state that it's not recommended to use this library in the production code. So, I prefer to avoid it. Am I wrong?

**Comment by adetaylor** [comment]
You're right! It's something I work on in my "spare time". I do believe it will get to the point where I remove that recommendation, but that's probably a few months off.
