### ISSUE TITLE
CxxVector::push_back

### ISSUE THREAD

**Issue by smessmer** [dtolnay/cxx#778]
Adding push_back/pop functionality (and other mutation functionality) to `CxxVector` would be helpful for `CxxVector`s containing types that rust can obtain (e.g. `CxxVector<CxxString>` or `CxxVector<SharedPtr<T>>`). Similarly, `CxxVector::new()` or `CxxVector::default()` would be helpful to create them from Rust.

**Comment by dtolnay** [comment]
Absolutely -- I would accept a PR adding `push_back` and `pop`. For a workaround in the meantime, it's fairly easy to expose your own push function to Rust implemented in C++:

```rust
// src/lib.rs

#[cxx::bridge]
mod ffi {
    struct Struct { test: i32 }

    unsafe extern "C++" {
        include!("example/include/example.h");

        fn vector_struct_push_back(vec: Pin<&mut CxxVector<Struct>>, val: Struct);
    }
}
```

```cpp
// include/example.h

#pragma once
#include <vector>

struct Struct;

void vector_struct_push_back(std::vector<Struct> &vec, Struct val);
```

```cpp
// src/example.cc

#include "example/src/lib.rs.h"

void vector_struct_push_back(std::vector<Struct> &vec, Struct val) {
  vec.push_back(std::move(val));
}
```

**Comment by dtolnay** [comment]
I published cxx 1.0.45 containing `CxxVector::push` and `CxxVector::pop`, with signatures matching the Rust standard library `Vec::push` and `Vec::pop`.

**Comment by smessmer** [comment]
thank you :)

**Comment by smessmer** [comment]
just noticed that it only works for primitive types. But kind of makes sense since pushing opaque types to it would only work if it's a `CxxVector<SharedPtr<T>>` which doesn't work yet https://github.com/dtolnay/cxx/issues/774

**Comment by smessmer** [comment]
actually, not entirely true. It would be helpful for `CxxVector<CxxString>::push` too
