### ISSUE TITLE
Can't use other libraries because of unsupported raw pointer

### ISSUE THREAD

**Issue by mikhailzagurskiy** [dtolnay/cxx#796]
I want to use the `opencv` crate in my project along with some specific library.

The specific library has the function `void processOneFrame(const void*data, const size_t size)`. 

Opencv has the function `opencv::core::Mat::as_raw_Mat()` [which returns](https://docs.rs/opencv/0.51.0/opencv/core/prelude/trait.MatTrait.html#tymethod.as_raw_Mat) the `const void*` type.

I want to pass the result of the `opencv` function to the function of specific library, but I can't declare method of the specific library inside `unsafe extern "C++"`.

If I defined it as:

```
fn processOneFrame(data: *const c_void, size: u64);
```

I have the following error:

```
 error[cxxbridge]: unsupported type: c_void
     ┌─ src/mod.rs:64:20
     │
  64 │       data: *const c_void,
     │                    ^^^^^^ unsupported type
```

If I define the function as:

```
fn processOneFrame(data: *const c_char, size: u64);
```

I have the following error:

```
error[E0308]: mismatched types
  --> test/src/main.rs:43:9
   |
43 |         frame.as_raw_Mat(),
   |         ^^^^^^^^^^^^^^^^^^ expected `i8`, found enum `c_void`
   |
   = note: expected raw pointer `*const i8`
              found raw pointer `*const c_void`
```

How should I define the function from the specific library, or how to convert one raw pointer into another?

**Comment by dtolnay** [comment]
There is no c_void built in right now but you can always define one easily:

```cpp
// example.h

#pragma once

using c_void = void;

const void *as_raw_Mat();
void processOneFrame(const void *p);
```

```rust
// main.rs

#[cxx::bridge]
pub mod ffi {
    extern "C++" {
        include!("include/example.h");

        type c_void;

        unsafe fn as_raw_Mat() -> *const c_void;
        unsafe fn processOneFrame(p: *const c_void);
    }
}

fn main() {
    unsafe {
        let p = ffi::as_raw_Mat();
        ffi::processOneFrame(p);
    }
}
```

**Comment by mikhailzagurskiy** [comment]
Didn't think in that way! Thank you.

**Comment by lerouxrgd** [comment]
As a follow-up on this, how can you handle the case where

```rs
#[cxx::bridge(namespace = foo)]
pub mod ffi {
    unsafe extern "C++" {
        include!("some/header.h"); // defines foo::processOneFrame(const void *p);

        type c_void;

        unsafe fn processOneFrame(p: *const c_void);
}
```

As it will generate a type `::foo::c_void` instead of just `c_void` ?
