### ISSUE TITLE
Mode for trivially movable std::string

### ISSUE THREAD

**Issue by adetaylor** [dtolnay/cxx#798]
I've been laboring under the misapprehension that `std::string` contains a self-referential pointer for the short-string optimization, and is therefore not trivially movable.

For at least some `std::string` implementations (libc++), this is [not the case](https://joellaity.com/2020/01/31/string.html).

Would you be open to supporting a mode in `cxx` where `CxxString` can be passed by value back and forth between C++ and Rust, and passed around as a first-class object in Rust?

Concerns:

* We believe this isn't guaranteed by any standard, and therefore is a property of the specific C++ library in use: [libstdc++ doesn't seem to share this property](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/bits/basic_string.h#L449). I'm not sure how best to communicate this "mode" to `cxx-macro` and the code generators - an environment variable? Or maybe we don't need it to be switchable, and we just explode with a great `static_assert` error message in case of trouble?
* `std::string` still has a destructor. We would need to implement `Drop`, and somehow we'd need to ensure that the `Drop` was only effective when the `CxxString` isn't held via a `UniquePtr`, `CxxVector` or similar. The only way I can think to do that is to add something like `is_owned_by_cpp(bool)` to `UniquePtrTarget` and then store a bit inside `CxxString`, which is not very nice. Any better ideas? (update: actually I think this is nonsense. The `CxxString` doesn't actually exist inside the `UniquePtr` so we wouldn't get double-destruction)
* Arguably if we're jumping through those hoops for a single C++ type which is movable but has a destructor, we should generalize it so that arbitrary `ExternType`s can benefit too. I don't have a design in mind.
* It might be useful to be able to take a `CxxString` _out of_ a `UniquePtr<CxxString>` and vice-versa, which is not a facility that currently exists. I don't see any reason why that would be _difficult_ (we would have to call through to new C++ methods which do a `std::move`) and presumably this could also apply to any `Trivial` type. I think it's orthogonal to this request, but this might accelerate the need for it.
* I haven't actually _checked_ that this `std::string` is trivially movable. It appears as though it should be.

**Comment by dtolnay** [comment]
I don't want this built into cxx. But it should be pretty easy to make your own libc++-specific string as an extern type:

```rust
pub struct CxxString {
    ????
}

unsafe impl ExternType for CxxString {
    type Id = type_id!("std::string");
    type Kind = cxx::kind::Trivial;
}

impl Drop for CxxString {
    fn drop(&mut self) {...}
}

impl Clone for CxxString {
    fn clone(&self) -> Self {...}
}

#[cxx::bridge]
mod ffi {
    extern "C++" {
        #[namespace = "std"]
        #[cxx_name = "string"]
        type CxxString = crate::CxxString;
    }

    impl UniquePtr<CxxString> {}
}
```

If there is something missing to make the above work, I would accept PRs for that.

**Comment by adetaylor** [comment]
Yes, I agree that should work. My reservation would be that people will want to write Rust code that can work interchangeably with both `&cxx::CxxString` and `&crate::CxxString`, but I suppose they can use a trait if they need to do that.
