### ISSUE TITLE
[Feature request] Allow macro inside cxx::bridge

### ISSUE THREAD

**Issue by mikhailzagurskiy** [dtolnay/cxx#807]
When we write a lot of similar wrappers, it would be great to use macro to simplify their declaration:

```
macro_rules! impl_interface {
  ($ty:ty) => {
    paste::item! {
       fn [<_I $ty _method1>](&self) -> u64 ;
    }
  }
}

#[cxx::bridge]
mod ffi {
  unsafe extern "C++" {
    impl_interface!(Class1);
    impl_interface!(Class2);
    impl_interface!(Class3);
    impl_interface!(Class4);
  }
}
```

I can do it in implementation, but can't in declaration

**Comment by andfoy** [comment]
I think this is a duplicate of https://github.com/dtolnay/cxx/issues/274

**Comment by mikhailzagurskiy** [comment]
Yes, thank you. It's a duplicate. Will close this.
