### ISSUE TITLE
Is it possible to use cxx for building rust bindings for a c++ library?

### ISSUE THREAD

**Issue by oronsh** [dtolnay/cxx#812]
Hello,
First of all, thank you for this amazing project.
I would like to write bindings for some c++ library, for what I can see in the tutorial, `cxx` is used to bridge rust code and c++ code into a rust binary (`main.rs`, `fn main() {}`)
Is it possible to create a rust lib without a main function that binds some c++ library?
Sorry if the question is stupid or anything, I myself am pretty new to rust.

**Comment by dtolnay** [comment]
It works the same whether or not there is a `main` function. As an example of binding a C++ library as a Rust library using cxx, see https://github.com/vi/gaborator-rs/blob/b9b4a4b130befa7fdca24515c32e522ccab3ca91/gaborator-sys/src/lib.rs.

**Comment by oronsh** [comment]
Thank you!
