### ISSUE TITLE
How to call a rust::Fn more than once with context

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/cxx#856]
*Moved from https://github.com/dtolnay/cxx/issues/114#issuecomment-830163853. @jerel*

<table><tr><td></td><td>

> The workaround for now is to pass context through manually via an opaque Rust type.

Is there any way today to repeatedly call the callback from C++ with the same context? The example given works great for a oneshot:
``` cc
void some_async(
    rust::Fn<void(rust::Box<Context> ctx, double ret)> done,
    rust::Box<Context> ctx) const
{
    done(std::move(ctx), 42.0);
}
```
but I'm unclear if it's possible today to accomplish this:
``` cc
    done(std::move(ctx), 42.0);
    done(std::move(ctx), 42.1);
```

</td><td></td></tr></table>

**Comment by dtolnay** [comment]
Hi @jerel, yes, you need to make the rust::Fn not destroy the context argument in that case. `fn(Box<Context>, Ret)` (i.e. `rust::Fn<void(rust::Box<Context>, Ret)>`) is not the right signature in that case because that function consumes ownership of the Box argument. Try using a reference for the closure argument instead, which does not consume ownership / destroy it as part of the function call.

Relevant Rust book chapters to explain the distinction between `Box<Context>` vs `&Context`: https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html, &ensp;https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html.

Demo:

```rust
// main.rs

#[cxx::bridge]
mod ffi {
    extern "Rust" {
        type Context;
    }

    unsafe extern "C++" {
        include!("dir/some.h");

        fn some_async(done: fn(&Context, f64), ctx: Box<Context>);
    }
}

pub struct Context(usize);

fn main() {
    ffi::some_async(
        |context, ret| println!("ctx={} ret={}", context.0, ret),
        Box::new(Context(1)),
    );
}
```

```cpp
// some.h

#pragma once
#include "rust/cxx.h"

struct Context;

void some_async(rust::Fn<void(const Context &ctx, double ret)> done,
                rust::Box<Context> ctx);
```

```cpp
// some.cpp

#include "dir/some.h"

void some_async(rust::Fn<void(const Context &ctx, double ret)> done,
                rust::Box<Context> ctx) {
  done(*ctx, 42.0);
  done(*ctx, 42.0);
}
```

**Comment by jerel** [comment]
Thanks @dtolnay, the detailed explanation was very helpful, I now have streaming over channels from C++ working in my application. 🎉  Thanks again
