### ISSUE TITLE
Allow #[main] in cxx::bridge

### ISSUE THREAD

**Issue by rcastill** [dtolnay/cxx#862]
The idea is to be able to use C++ as entrypoint. Usecase: existing codebase that I want to enhance with rust lib. I could not find a way to do this. The closest I got was to create a main.rs file without main() so it would take the main function defined in my c++ codebase, but then, Rust complains that main() must be defined at the root of the crate, -or- mark it with #[main].

**Comment by dtolnay** [comment]
If I understand correctly, this is already supported. See https://cxx.rs/binding/cxxvector.html#example or https://cxx.rs/binding/slice.html#example for examples that have entrypoint implemented in C++.

**Comment by rcastill** [comment]
! Thanks
