### ISSUE TITLE
Static linking with musl

### ISSUE THREAD

**Issue by rcastill** [dtolnay/cxx#863]
I am trying to statically compile using musl. I'm having the following problem:

```
undefined reference to `__dso_handle'
```

**Note**: that --target is set to x86_64-unknown-linux-musl (or aarch64 when crosscompiling). That uses my musl-g++ compiler automatically, I verified it using `Builder::get_compiler`.

I also have `.static_flag(true)` in build.rs.

I understand that __dso_handle is a gnu extension?

Any clues?

**Comment by dtolnay** [comment]
Hi Rodolfo, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community (Discord, Users forum, possibly the Rust subreddit).
