### ISSUE TITLE
c++ enum nested in struct

### ISSUE THREAD

**Issue by remifontan** [dtolnay/cxx#866]
does CXX support C++ enum defined within a struct?

pseudo c++ code:

```cpp
struct FOO {
    enum BAR { a, b, c };

    BAR bar;
};
```

how would I defined the ffi mod to handle this case?

```rust

#[cxx::bridge]
mod ffi {
    enum BAR { a, b, c }
    unsafe extern "C++" {
        include!("pathtomycppcode.h");
        type BAR;
    }
}
```

when building I would get an error like ` error: no type named BAR ... did you mean 'FOO::BAR'?`

is there some sort of attribute I could use to tag the rust enum BAR that it is actually FOO::BAR in c++?

cheers.

**Comment by dtolnay** [comment]
I think it should work if you add an appropriate `using` into any of the included headers.

```cpp
using FOO_BAR = FOO::BAR;
```

and then bind `FOO_BAR` as the enum in the bridge.

**Comment by remifontan** [comment]
thanks for the quick reply. I followed you suggestion and it works! :-)
