### ISSUE TITLE
Which string passing method has less overhead?

### ISSUE THREAD

**Issue by alexxbb** [dtolnay/cxx#877]
I would appreciate if someone could clear this for me.
I wonder which one of these two ways of passing strings from Rust has less overhead?

I'd assume **call_2/example_2** is more expensive do to allocation on the Rust side (`.to_string()`) and then a second allocation on c++ side (`auto str = std::string(s)`). 
**call_1/example_1** on the other hand creates a C++ string on stack according to the docs, does it mean there's not allocation happening at all? Even for *&[u8]* ?

```rust
#[cxx::bridge]
mod ffi {
    unsafe extern "C++" {
        fn example_1(s: &CxxString);
        fn example_2(s: &str);
    }
}
```

```rust
fn call_1(s: &str) {
    let_cxx_string!(cxx_s = s);
     ffi::example_1(&cxx_s);
}
fn call_2(s: &str) {
    let s = s.to_string();
     ffi::example_2(&s);
}
```

Use on the other side:
```cpp
void example_1(std::string &str) {
    some_func(str);
}

void example_1(rust::Str str) {
     auto _str = std::string(str);
     some_func(str);
}

```

Thanks!

**Comment by dtolnay** [comment]
If this matters for your use case, then you would need to benchmark on data that is representative of your personal use case. This sort of thing depends on the data and the build flags being used.

**Comment by CAD97** [comment]
In `call_2`, there's no need to call `.to_string()` at all, as `example_2` takes `&str` to begin with. For `let_cxx_string!`, it constructs a `std::string` on the Rust stack, but that `std::string` may itself contain a heap allocation if its small string optimization does not apply. Thus, with a properly written

```rust
#[cxx::bridge]
mod ffi {
    unsafe extern "C++" {
        fn example_1(s: Pin<&mut CxxString>);
        fn example_2(s: &str);
    }
}

fn call_1(s: &str) {
    let_cxx_string!(cxx_s = s);
    ffi::example_1(cxx_s);
}
fn call_2(s: &str) {
    ffi::example_2(s);
}
```

```cpp
void example_1(std::string &str) {
    some_func(str);
}

void example_2(rust::Str str) {
     auto _str = std::string(str);
     some_func(_str);
}
```

there are the same number of copies/allocations: one, to go from `&str`<sub>Rust</sub> to `std::string`<sub>C++</sub>.

Generally, if you have full control over the FFI border, it's probably better to send `&str`</sub>Rust</sub>, as that gives the C++ side more options what to do with it.

---

There is one case where using `&str` is definitely going to be better, though: if `some_func` accepts `std::string&&` (an rvalue "move" reference). Then, by writing `example_2` as

```cpp
void example_2(rust::Str str) {
     some_func(std::string(str));
}
```

you allow the C++ code to effectively take ownership of the `std::string` constructed here.

---

Of course, this is exclusively looking at copies/allocations, and this may not actually be the correct answer depending on your exact configuration and workload. Get something that works first, then benchmark and see if it's even worth spending effort optimizing.

**Comment by alexxbb** [comment]
I ended up using both methods. Whenever possible, I call methods directly on extern types ( those which take **self: & Type, s: &CxxString)** I use _let_cxx_string!_, otherwise _&str_ which is generally more convenient.

It's not a hot loop in my case so in the end it really doesn't matter which method is more optimal. 

P.S. Couldn't property benchmark it coz I'm wrapping a network library and it's to much hassle to do.

Thanks guys!
