### ISSUE TITLE
Linking against multiple static libraries that use cxx

### ISSUE THREAD

**Issue by JBBgameich** [dtolnay/cxx#883]
In my C++ project I have two rust crates that export a C++ API using cxx.

That setup ends in a bunch of linking errors like this:
```
/usr/bin/ld: libangelfish_readability.a(cxx-546393ec83734d88.cxx.77528ncj-cgu.12.rcgu.o): in function `cxxbridge1$exception':
/home/jbb/.cargo/registry/src/github.com-1ecc6299db9ec823/cxx-1.0.49/src/symbols/exception.rs:6: multiple definition of `cxxbridge1$exception'; libangelfish_adblock.a(cxx-506fb85a29953a06.cxx.6ziszbha-cgu.12.rcgu.o):/home/jbb/.cargo/registry/src/github.com-1ecc6299db9ec823/cxx-1.0.49/src/symbols/exception.rs:6: first defined here
/usr/bin/ld: libangelfish_readability.a(cxx-546393ec83734d88.cxx.77528ncj-cgu.12.rcgu.o): in function `cxxbridge1$str$from':
/home/jbb/.cargo/registry/src/github.com-1ecc6299db9ec823/cxx-1.0.49/src/symbols/rust_str.rs:18: multiple definition of `cxxbridge1$str$from'; libangelfish_adblock.a(cxx-506fb85a29953a06.cxx.6ziszbha-cgu.12.rcgu.o):/home/jbb/.cargo/registry/src/github.com-1ecc6299db9ec823/cxx-1.0.49/src/symbols/rust_str.rs:18: first defined here
```

Can I do anything about it apart from moving everything into one crate, or is this a general limitation?

**Comment by Geobert** [comment]
What's the status on this? Any clue if it's a limitation or if some method is available to make that work?

**Comment by dtolnay** [comment]
According to https://cxx.rs/build/other.html (source: @adetaylor in #345):

> you first need to use `rustc` and/or `cargo` to generate a ***single* Rust `staticlib` target** and pass that into your foreign linker invocation.
>
> - If you need to link multiple Rust subsystems, you will need to generate a ***single* `staticlib`** perhaps using lots of `extern crate` statements to include multiple Rust `rlib`s. Multiple Rust `staticlib` files are likely to conflict.

That all seems consistent with what you've described. Rust does not expose any way for a C++ linker to link multiple Rust staticlibs. That part always has to be done by Rust's linker.

https://github.com/rust-lang/rust/issues/73632 has more extensive discussion of this situation.
