### ISSUE TITLE
Bridge between Rust and a C++ lib

### ISSUE THREAD

**Issue by Geobert** [dtolnay/cxx#899]
Hi, 

Sorry if this is a dumb question, but after reading the cxx book again and again, I can't get my head around how to bridge a C++ library with Rust.
I'm trying to understand how Rust can use a class defined in a C++ lib. 

All the example I can find are calling C++ code that is written within the crate.
What am I missing? Does my use case require something like `autocxx`?

**Comment by dtolnay** [comment]
Hi Geobert, sorry that no one was able to provide guidance here. If this is still an issue, you could try taking this question to any of the resources shown in https://www.rust-lang.org/community and someone may be available to work through it with you. Either of the Discords (https://discord.gg/rust-lang, https://discord.gg/rust-lang-community) or the Users forum would be appropriate for this.
