### ISSUE TITLE
Build using CMake with dynamic linking and shared object file

### ISSUE THREAD

**Issue by OscarTHZhang** [dtolnay/cxx#900]
I am working on a project where I would like to compile my Rust code into a C++ callable library with a few functions and shared types, structs, and enums. I am referencing this example here: https://github.com/XiangpengHao/cxx-cmake-example but I encountered some issues. Basically it printed something like `symbol not found` and gave me lots of unreadable object code. 

I also checked out the cxx.rs website and it said that 
> Use your C++ linker. In this case, you first need to use rustc and/or cargo to generate a single Rust `staticlib` target and pass that into your foreign linker invocation.

In this case, I wonder is it possible to build link a `dylib` Rust target with my existing C++ code using cxx?

**Comment by kydos** [comment]
I have a similar use case, but something I'd like to report is that rust functions that are not called in C++ code seams to be generated into a namespace whose prefix is  ```cxxbridge```. Only if a rust function is referenced by the C++ code the symbol appears to be correct (as you can verify with ```nm``` and ```c++filt```.

Is that intended? Is there an option to disable this behaviour and expose all symbols?

Thanks!

**Comment by david-cattermole** [comment]
Hello @OscarTHZhang,

It might not be the most elegant approach (I'm sure someone could improve it), however if you need a working example to dissect I have a toy project here:
https://github.com/david-cattermole/cxx-demo-example

The approach has been applied to this non-toy project:
https://github.com/david-cattermole/OpenCompGraph

My examples compile the rust code as `crate_type = ["staticlib"]`, and I then use CMake `add_library(${target_lib} SHARED ${source_files})` to create the dynamic library using the native C++ compiler. 

So far I have been able to call from Rust to C++ and Rust to C++, and sharing structs across the boundary with no unsafe code at all. I also link to many other C++ and C libraries and link all of them together with the native C++ compiler and linker.
