### ISSUE TITLE
Safety question: "ABI compatible with C++ type but not Rust type" comments

### ISSUE THREAD

**Issue by sbrocket** [dtolnay/cxx#905]
There are a number of comments in `src/` to the effect of `// ABI compatible with C++ rust::String (not necessarily alloc::string::String).` However, `RustString::from` for example `mem::transmute`'s between `alloc::string::String` and itself. Why is that transmute safe in the context of that comment?

For context, see https://fuchsia-review.googlesource.com/c/fuchsia/+/527961. One of our unsafe reviewers had a number of questions on updating our vendored cxx version to 1.0.49.

**Comment by dtolnay** [comment]
Transmuting has nothing to do with ABI. For example transmuting i32 \<-\> \[u8; 4\] is well defined and widespread, even though those have different ABI. ABI is only relevant to redeclaring and interacting with an extern signature.

**Comment by sbrocket** [comment]
Indeed, makes sense. Thanks for the quick answer.
