### ISSUE TITLE
Explicitly instantiating WeakPtr does not impl WeakPtrTarget

### ISSUE THREAD

**Issue by jsgf** [dtolnay/cxx#926]
If I have
```
#[cxx::bridge]
mod ffi {
    extern "C++" {
        type Foo;
    }
    impl WeakPtr<Foo>;
}

fn foo_thing(foo: WeakPtr<ffi::Foo>) {}
```

It fails with ``` the trait `WeakPtrTarget` is not implemented for `Foo` ```.

This also happens with `UniquePtr` (and I'd assume `SharedPtr`, but I didn't test that).

It's not clear to me whether it's *intended* for these `impl`s to generate these internal trait impls, but it would be nice to have some mechanism to do it. As a workaround I have a dummy function taking `WeakPtr<Foo>` to force generation.

**Comment by Demiguise** [comment]
@jsgf Do you happen to know what the issue was? I have roughly the same issue and can't see what to add, despite looking at all the tests.

**Comment by jsgf** [comment]
I don't remember specifically, but I think I may have got my ffi and non-ffi types mixed up:
```
struct MyThing(ffi::MyThing);

fn foo(foo: WeakPtr<MyThing>) { ... } // WRONG: should be ffi::MyThing


```
