### ISSUE TITLE
Allow overriding receiver to be `&const Self` for non-const C++ member functions

### ISSUE THREAD

**Issue by Eadword** [dtolnay/cxx#936]
I don't see an existing issue for this so here we go...

I have run into an issue with the current treatment of C++ `const` member functions as being equivalent to Rust members accepting `&self`.

- C++ defines a constant member as a function which does not modify the object.
- Rust defines a `&self` receiving function as one which does not mutate the object but allows for internal mutability under verifiably safe conditions (Cell/Mutex/...)

My specific case is something akin to (forgive my rough example)
```c++
class Foo {
  Mutex mutex;
  int data;

public:
  Foo(): data(0) {} 

  // this cannot be `const` because it modifies the obj
  void doThing() {
    auto lock = mutex.lock();
    data++;
  }
}
```

So in Rust a native implementation would look like
```rust
pub struct Foo {
  data: Mutex<i32>,
}

impl Foo {
  pub fn doThing(&self) {
    *self.data.lock() += 1
  }
}
```

But then using CXX we have a problem because we cannot define
```rust
#[cxx::bridge]
mod ffi {
  unsafe extern "C++" {
    type Foo;
    fn doThing(&self);
  }
}
```

without (in my case) getting the error
> cannot convert from 'void (__cdecl Foo*)()' to 'void (__cdecl Foo*)() const'

Which means we now need to write it as a mut which means we have to have another mutex which is non-ideal for performance reasons and also makes things a lot less easy to use.

My proposal specifically is to make the following (or some variant thereof) valid
```rust
#[cxx::bridge]
mod ffi {
  unsafe extern "C++" {
    type Foo;
    fn doThing(self: &const Self); // <- developer is explicitly stating this is valid
  }
}
```

**Comment by dtolnay** [comment]
The closest C++ equivalent of the Rust implementation you wrote:

```rust
pub struct Foo {
    data: Mutex<i32>,
}

impl Foo {
    pub fn doThing(&self) {
        *self.data.lock() += 1
    }
}
```

is:

```cpp
class Foo {
  mutable Mutex mutex;
  mutable int data;

public:
  Foo() : data(0) {}

  void doThing() const {
    std::lock_guard<std::mutex> guard(mutex);
    data++;
  }
};
```

which is perfectly fine to bind via cxx. That is the recommended implementation if this is first party code. The interpretation of const == threadsafe is common, well known, and is a design pattern in the C++ standard library.

**Comment by Eadword** [comment]
As a Rust developer I see where you are coming from, and if it were my code to maintain, I would make the change. However, multiple C++ devs seem to disagree very strongly with your stance. While I am not going to post their arguments here because I do not think this is an appropriate place to argue about C++ best practices or ideology, please consider the following:

Even if modern C++ does define `const` as threadsafe, it seems it is not widely accepted or widely known especially for code which is not a public-facing interface. Further, **we don't always have control over the code we need to interface with, and interfacing with C++ should not require changes to working C++ code**.

For these reasons and because I wish to not irritate everyone with my Rust evangelism, I am still in favor of allowing the cxx crate to manually override the receiver to a `&const Self` since it means I can make the assertion in the foreign interface code (which is inherently unsafe) and take responsibility.

I will work on a PR for this.

**Comment by dtolnay** [comment]
Shrug -- I feel that this has been a consensus position for nearly 10 years at this point. Herb Sutter, Bjarne Stroustrup in *The C++ Programming Language, Fourth Edition*, and everybody else who typically gets involved in such things has advocated it. https://channel9.msdn.com/posts/C-and-Beyond-2012-Herb-Sutter-You-dont-know-blank-and-blank is a good explainer.

> Remember, the fact that people expect this is not new. People have been expecting this for 25 years, and we've had to keep telling them "no it's really not that way, it's this embarrassing thing, sort of 'logically const' and I'll explain it to you over lunch one day", right? No more! Const means thread-safe.

> We used to say "const means logically const". And that's kinda awkward, but you know we got over it and that's what we taught people. The new reality is const means thread-safe -- either bitwise const or internally synchronized.

> We used to teach "mutable == not observably non-const", which is kinda awkward, but it's what we taught. Now it's much clearer. Mutable means thread-safe too. It means bitwise const or internally synchronized.

I'll go ahead and close the issue since I don't think I would want to take a PR for this. The cxx crate is fundamentally geared around "cooperative FFI", which is why it's okay for the readme to explain that handling any arbitrary signature (particularly a signature that is antagonistic to being bound from Rust) is not a goal.

**Comment by Eadword** [comment]
Even though this has been closed, I wanted to follow up on this if anyone else stumbles into it and because I think we had a misunderstanding fundamentally and I at least _think_ I see now.

My solution to this (without changing a bunch of C++ code that does not belong to me), was to create wrapper C++ code. My project now looks like:

```
src/
  lib.rs
  somemod.rs
  somemod.hpp
  somemod.cpp
  othermod.rs
  othermod.hpp
  othermod.cpp
  ...
```

Which I have found to be a somewhat clean way of also creating more support for things such as being able to return a rust vec from C++ or create a builder struct to handle some opaque types. It also means things like `const` and `mutable` can be added as needed without having to "clutter" (co-workers' word choice) an existing repo.

My fundamental misunderstanding was that `cxx` is trying to make these wrappers unneeded, and really what I should have seen is that it makes C wrappers unneeded. Writing a C++ wrapper is far more pleasant. (And if you are writing code from scratch in both langs you can probably avoid them altogether).

It is my belief that in the future cxx could get good enough to prevent needing any wrappers at all, but at least right now this wrapper approach seems optimal for at least my use case.
