### ISSUE TITLE
Is there any way to add folders to the list of import directories for Angle Bracket imports?

### ISSUE THREAD

**Issue by Supermath101** [dtolnay/cxx#944]
The title basically says it all. By angle brackets I mean `<` and `>`. I'm not sure if the `.include("...")` method on the builder in `build.rs` does it or not, but it seems like it's not working. The C++ code would look like this:
```c++
#include <MyCustomHeader.h>
// ...
```

**Comment by dtolnay** [comment]
https://docs.rs/cxx-build/1.0.56/cxx_build/static.CFG.html#cfgexported_header_dirs shows some examples of how to do this.

**Comment by Supermath101** [comment]
I just ended up doing:
```rust
.flag("-isystem").flag("/path/to/headers");
```

**Comment by dtolnay** [comment]
Great!
