### ISSUE TITLE
How do you clear a Vec<T> from C++?

### ISSUE THREAD

**Issue by joverwey** [dtolnay/cxx#950]
I have a shared struct that contains a Rust Vec.

``` Rust
struct Foo {
    values: Vec<f32>
}
```

This becomes a `rust::cxxbridge::Vec` on the C++ side.
Unfortunately this class doesn't seem to have a `clear` method which means I cannot re-use the same vector.

How can I clear an existing `Vec` from C++?

**Comment by dtolnay** [comment]
```rust
#[cxx::bridge]
mod ffi {
    extern "Rust" {
        fn clear_vec(v: &mut Vec<f32>);
    }
}

fn clear_vec(v: &mut Vec<f32>) {
    v.clear();
}
```

This is callable from C++ as `clear_vec(foo.values)`.

Separately, we could build a `clear` member function into rust::Vec if somebody sends a PR.
