### ISSUE TITLE
Bazel build reruns cxxbridge-cmd on each build

### ISSUE THREAD

**Issue by jon-chuang** [dtolnay/cxx#964]
Leverage infrastructure in Bazel not to rerun on each build if deps have not changed.

**Comment by dtolnay** [comment]
The bazel stuff in this repo is only intended to be used by our own CI jobs. I just checked and that job does not execute cxxbridge-cmd multiple times on the same input.

**Comment by jon-chuang** [comment]
yes, I believe I made a mistake, it seems I happened to have been unwittingly changing dependencies...
