### ISSUE TITLE
`catch_unwind` and `noexcept`

### ISSUE THREAD

**Issue by WilliamVenner** [dtolnay/cxx#965]
Hi there,

I noticed that cxx will add `noexcept` to `extern "C++"` functions, but always tries to catch panics on `extern "Rust"` functions.

I am concerned about performance. I have a function that is extremely hot, and I know for absolute certainty that it cannot panic. How do I turn off the unwind catching present here?:

https://github.com/dtolnay/cxx/blob/3eba08594cc356088819243af23f14e1b6447ec4/src/unwind.rs#L7-L19

**Comment by dtolnay** [comment]
This code was removed in #970.
