### ISSUE TITLE
Possible to use build variables?

### ISSUE THREAD

**Issue by dunmatt** [dtolnay/cxx#986]
I suspect the answer to this is "no, that's not a thing because C++ is prohibitively complex", but I'm hoping there's a way to set variables that the preprocessor can read.  For legacy reasons that I don't actually know I have a header file that says:

    #if FOO
    // define stuff!
    #endif

and CMake knows whether it wants to set FOO, but I'm not seeing a way to pass that information through the `cxxbridge` calls.  Is there something I can do, or should I start refactoring to eliminate the preprocessor if?

**Comment by dtolnay** [comment]
Build variables are not relevant to CXX because by design we simply don't look at the header. CXX does not parse it or run the C preprocessor on it or compile it.

When compiling the C++ side of your application is when you would need to set those variables, but that is independent of CXX.

**Comment by dtolnay** [comment]
For example if you were using Cargo for the C++ build, they're set with https://docs.rs/cc/1.0.72/cc/struct.Build.html#method.define.

See https://github.com/dtolnay/cxx/pull/987/files.

**Comment by dunmatt** [comment]
Hmmm, then it's clear I don't understand how our build works / should work / has ever worked.  Thanks for the info, it at least points me away from certain rabbit holes!
