### ISSUE TITLE
Is there currently a way to do conditional compilation?

### ISSUE THREAD

**Issue by laptou** [dtolnay/cxx#989]
I want to bind to some C++ methods which only exist on Android. However, if I try to do something like this:

```rust
        #[cfg(target_os = "android")]
        type CallInvokerHolder;

        #[cfg(target_os = "android")]
        pub fn getCallInvoker(self: Pin<&mut CallInvokerHolder>) -> SharedPtr<CallInvoker>;
```

I get the following error:
```plain
  error[cxxbridge]: unsupported attribute
      ┌─ src/ffi.rs:326:5
      │
  326 │     #[cfg(target_os = "android")]
      │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unsupported attribute
```

Is there a workaround?

**Comment by dtolnay** [comment]
This is definitely something we can support, but it's not implemented yet. 

Basically in Cargo-based builds `cxx-build` would need to examine [CARGO_CFG_TARGET_OS](https://doc.rust-lang.org/1.57.0/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) in the build script's environment to decide whether or not to write those types/functions into the generated C++ code, with no other action required on the user's part other than writing `cfg(...)` inside their cxx::bridge module; and Bazel/Buck/CMake/etc would need the build system to pass something like `--cfg=target_os=android` / `--cfg=target_os=linux` as part of their `cxxbridge` invocation.

For now the easiest workaround would be to move the android-specific signatures to a different cxx::bridge module in a different file, and gate that whole file with `#[cfg(target_os = "android")]`.

Something like:

```rust
// lib.rs

#[cfg(target_os = "android")]
mod android;
```

```rust
// android.rs

#[cxx::bridge]
mod ffi {
    extern "C++" {
        type CallInvokerHolder;
        fn getCallInvoker(self: Pin<&mut CallInvokerHolder>) -> SharedPtr<CallInvoker>;
        ...
    }
}
```

```rust
// build.rs

let mut bridge_modules = vec!["src/lib.rs"];
if std::env::var_os("CARGO_CFG_TARGET_OS").unwrap() == "android" {
    bridge_modules.push("src/android.rs");
}
cxx_build::bridges(bridge_modules)
    ...
    .compile(...);
```

**Comment by laptou** [comment]
Thanks for the tip! This is exactly what I ended up doing.

**Comment by dtolnay** [comment]
I published an implementation of `#[cfg(...)]` conditional compilation in cxx 1.0.63. In Cargo-based builds it should just work. In non-Cargo builds you'll need your build system to pass `--cfg` flags to the cxxbridge CLI just like you'd pass to `rustc`.

**Comment by lucas-zee** [comment]
Just bumped my cxx version (build and non build versions) to 1.0.63. Then doing:

```
#[allow(dead_code)]
#[cxx::bridge]
pub(crate) mod ffi {
       #[cfg(debug_assertions)]
       unsafe extern "C++" {
            unsafe fn do_something(
                context: SharedPtr<Context>,
                buffer: *const u8,
                size: usize,
        ) -> bool;
       }
```

gives undefined reference error on

```
e::ffi::do_something':
          /workspaces/something/src/bridge.rs:108: undefined reference to `cxxbridge1$do_something'
          collect2: error: ld returned 1 exit status

help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
```

**Comment by dtolnay** [comment]
There are a few special cfgs that Cargo conceals from build scripts. I added a workaround for that one in cxx-build 1.0.64.
