### ISSUE TITLE
Missing rust::String implementation when compiled with cxxbridge?

### ISSUE THREAD

**Issue by dunmatt** [dtolnay/cxx#991]
Starting at the beginning, I'm sure this is me not having a good handle on how this is all supposed to work... but for the life of me I don't see how this is supposed to work.  Starting with

    ❯ cat test.rs
    #[cxx::bridge]
    pub mod ffi {
      pub struct Example {
        field: String,
      }
    }

When I run `cxxbridge test.rs` it produces almost exactly the same output as when I run `cxxbridge test.rs --header`.  The one and only difference between the generated cpp file and the generated header is that the header starts with `#pragma once`.   After that first line the two are character for character identical (double checked by cutting the pragma line and then comparing `sha1sum`s)... which seems wrong.

At first I was content to ignore the counterintuitive generated code, but it also crashes at run time:  `undefined symbol: _ZNK4rust10
cxxbridge16StringcvNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEv`.  Any idea what I'm doing wrong?

**Comment by dunmatt** [comment]
I should add

    ❯ cxxbridge --version
    cxxbridge 1.0.60

**Comment by dtolnay** [comment]
rust::String corresponds to a Rust type. Its methods are implemented in Rust. If you are examining only C++ code, they're not gonna be there.

You need to compile and link the `cxx` crate (including its Rust and C++ parts) in order to get those methods.

**Comment by dunmatt** [comment]
Please forgive my stupid questions, I'm not a build engineer and CMake makes me regret my choice of professions. 

Does that mean that using Cargo is mandatory?  I looked at one of the CMake example repos, and it seemed to be based on a Cargo.toml file and a build.rs file.

My situation is that one project has C++, and the other has Rust and depends on the C++ project.  The whole thing is orchestrated/obscured by CMake.  Originally using `cxxbridge` seemed like a natural way to avoid having to move a bunch of code between the projects, but now that seems unavoidable?   Would I be better off moving all the cxx stuff into the C++ side or would that just create the reflection of the problem where the Rust side wouldn't know how to link?  Or is it even possible for you to advise on that without seeing our build?

Is it possible to the Rust side and the C++ side separately?  If not, is it typically easier to put Rust into a C++ project or vice versa?

**Comment by dtolnay** [comment]
Cargo is definitely not mandatory &mdash; for example my work codebase is using cxx with Buck without Cargo involved, and both `bazel build ...` and `buck build ...` in this repo compile cxx and our test suite without Cargo involved.

As someone who is also not a build engineer, my understanding is that CMake is disproportionately more of a pain in the ass than Bazel and Buck, so I'm guessing the folks that made those example repos put Cargo in there to escape some of the pain. It's certainly not required and you can wrangle CMake to do what Buck or Bazel are doing with enough effort.

**Comment by dunmatt** [comment]
Yeah, based on those build files I think it's safe to say that CMake is exponentially more of a PITA.  Also based on those files, I believe I've gotten myself sorted out by vendoring your cc and h files and adding them as a regular C++ library in our build.  Thank you so much for the help!
